# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-07 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banquet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banquetteattendant',
            name='wants_vegetarian_food',
            field=models.BooleanField(default=False),
        ),
    ]
