# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-07 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banquet', '0002_auto_20171007_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banquetteattendant',
            old_name='wants_vegetarian_food',
            new_name='wants_vegan_food',
        ),
    ]
