# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-07 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banquet', '0003_auto_20171007_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='banquetteattendant',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
