# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banquet', '0004_auto_20180910_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietarypreference',
            name='alcohol',
            field=models.BooleanField(default=True),
        ),
    ]
