# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-07 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banquet', '0004_banquetteattendant_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='banquetteattendant',
            name='ticket_type',
            field=models.CharField(choices=[('company', 'Company Representative Ticket'), ('student', 'Student Ticket')], default='company', max_length=35),
        ),
    ]
