# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-02 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banquet', '0005_auto_20181002_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='dietary_restrictions',
            field=models.ManyToManyField(blank=True, to='people.DietaryRestriction'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email_address',
            field=models.EmailField(blank=True, max_length=75, null=True, verbose_name='E-mail address'),
        ),
    ]
