# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banquet', '0005_dietarypreference_alcohol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietarypreference',
            name='alcohol',
        ),
        migrations.AddField(
            model_name='participant',
            name='alcohol',
            field=models.BooleanField(default=True),
        ),
    ]
