# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-07 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("banquet", "0006_auto_20181002_1440"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dietarypreference",
            name="banquet",
        ),
        migrations.AddField(
            model_name="invitation",
            name="banquet",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="banquet.Banquet",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invitation",
            name="denied",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="token",
            field=models.CharField(default=uuid.uuid4, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name="DietaryPreference",
        ),
    ]
