# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-07 19:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("banquet", "0007_auto_20181007_1035"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="banquet_invitation_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="token",
            field=models.CharField(
                default=uuid.uuid4, max_length=255, null=True, unique=True
            ),
        ),
    ]
