# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-10 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banquet', '0008_auto_20171007_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banquetteattendant',
            name='ticket_type',
            field=models.CharField(choices=[('company', 'Company Representative Ticket'), ('student', 'Student Ticket')], default='student', max_length=35),
        ),
    ]
