# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-10 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banquet', '0009_auto_20171010_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanquetTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_name', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'ordering': ['ticket_name'],
            },
        ),
    ]
