# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("banquet", "0010_auto_20181011_1326"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="seat",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="banquet.Seat",
            ),
        ),
        migrations.RemoveField(
            model_name="seat",
            name="participant",
        ),
        migrations.AlterUniqueTogether(
            name="seat",
            unique_together=set([("table", "name")]),
        ),
        migrations.AlterUniqueTogether(
            name="table",
            unique_together=set([("banquet", "name")]),
        ),
    ]
