# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-10 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banquet', '0010_banquetticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banquetticket',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='banquetticket',
            old_name='ticket_name',
            new_name='name',
        ),
    ]
