# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-10 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banquet', '0011_auto_20171010_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banquetteattendant',
            name='ticket_type',
            field=models.CharField(choices=[('company', 'Company Ticket'), ('student', 'Student Ticket')], default='student', max_length=35),
        ),
    ]
