# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banquet', '0012_auto_20171010_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banquetteattendant',
            name='ticket_type',
        ),
    ]
