# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("banquet", "0014_auto_20181028_1411"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitationgroup",
            name="banquet",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="banquet.Banquet",
            ),
            preserve_default=False,
        ),
    ]
