# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-24 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banquet', '0015_auto_20171020_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banquetteattendant',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('not_specify', 'Prefer not to specify')], max_length=100),
        ),
    ]
