# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banquet", "0015_invitationgroup_banquet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="price",
            field=models.PositiveIntegerField(verbose_name="Price (SEK)"),
        ),
    ]
