# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-09 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banquet', '0016_auto_20171024_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banquetteattendant',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banquet.BanquetTable'),
        ),
    ]
