# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-15 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banquet', '0017_auto_20171109_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banquetteattendant',
            options={'ordering': ['first_name', 'last_name'], 'permissions': (('can_seat_attendants', 'Can seat attendants'),)},
        ),
    ]
