# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-14 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banquet', '0017_afterpartyticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afterpartyticket',
            name='email_address',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='E-mail address'),
        ),
        migrations.AlterField(
            model_name='afterpartyticket',
            name='paid_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='afterpartyticket',
            name='paid_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
