# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banquet', '0018_auto_20171115_0955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banquetteattendant',
            options={'ordering': ['first_name', 'last_name'], 'permissions': (('base', 'Banquet'), ('can_seat_attendants', 'Can seat attendants'))},
        ),
    ]
