# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-15 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banquet', '0019_auto_20181114_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='afterpartyticket',
            name='charge_stripe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
