# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 09:15
from __future__ import unicode_literals

import banquet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banquet", "0020_afterpartyticket_charge_stripe"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="token",
            field=models.CharField(
                default=banquet.models.get_random_32_length_string, max_length=32
            ),
        ),
    ]
