# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("banquet", "0022_auto_20181117_0923"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seat",
            options={"ordering": ["table", "name"]},
        ),
        migrations.AlterModelOptions(
            name="table",
            options={"ordering": ["banquet", "name"]},
        ),
    ]
