# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-18 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banquet", "0024_auto_20181118_1847"),
    ]

    operations = [
        migrations.AddField(
            model_name="seat",
            name="left",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="seat",
            name="top",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
