# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banquet', '0026_participant_attended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='attended',
            new_name='ticket_scanned',
        ),
    ]
