# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-10 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banquet', '0027_auto_20181119_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='giveaway',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
