# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-10 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banquet", "0028_participant_giveaway"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="part_of_matching",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], default=False
            ),
        ),
    ]
