# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-21 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banquet', '0029_invitation_part_of_matching'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='dietary_restrictions_other',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
