# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-25 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("banquet", "0031_auto_20190921_1508"),
        ("banquet", "0028_tablematching"),
    ]

    operations = []
