# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-22 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banquet", "0033_participant_has_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="afterpartyticket",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="afterpartyticket",
            name="email_address",
            field=models.EmailField(
                default=False, max_length=75, verbose_name="E-mail address"
            ),
        ),
        migrations.AlterField(
            model_name="afterpartyticket",
            name="name",
            field=models.CharField(default=False, max_length=75),
        ),
    ]
