# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-15 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banquet", "0034_afterpartyinvitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="afterpartyinvitation",
            name="email_address",
            field=models.EmailField(max_length=75, verbose_name="E-mail address"),
        ),
        migrations.AlterUniqueTogether(
            name="afterpartyinvitation",
            unique_together=set([("banquet", "email_address")]),
        ),
    ]
