# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-25 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banquet', '0035_auto_20191022_1833'),
        ('banquet', '0035_auto_20191015_1759'),
    ]

    operations = [
    ]
