# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-26 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banquet", "0036_merge_20191025_0639"),
    ]

    operations = [
        migrations.AddField(
            model_name="banquet",
            name="afterparty_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
