# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-27 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banquet", "0037_banquet_afterparty_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="banquet",
            name="afterparty_price",
            field=models.PositiveIntegerField(default=75, verbose_name="Price (SEK)"),
        ),
    ]
