# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-27 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banquet", "0038_banquet_afterparty_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="afterpartyticket",
            name="inviter",
            field=models.CharField(
                blank=True,
                max_length=75,
                null=True,
                verbose_name="Full name of the inviter",
            ),
        ),
    ]
