# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-27 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banquet", "0039_afterpartyticket_inviter"),
    ]

    operations = [
        migrations.AddField(
            model_name="banquet",
            name="afterparty_price_discount",
            field=models.PositiveIntegerField(
                default=50, verbose_name="After Party Discounted Price (SEK)"
            ),
        ),
        migrations.AlterField(
            model_name="banquet",
            name="afterparty_price",
            field=models.PositiveIntegerField(
                default=75, verbose_name="After Party Price (SEK)"
            ),
        ),
    ]
