# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-27 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banquet", "0040_auto_20191027_1620"),
    ]

    operations = [
        migrations.AddField(
            model_name="afterpartyticket",
            name="has_paid",
            field=models.BooleanField(default=False),
        ),
    ]
