# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-27 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banquet', '0041_afterpartyticket_has_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='afterpartyticket',
            name='banquet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banquet.Banquet'),
        ),
    ]
