# Generated by Django 2.2.24 on 2023-10-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banquet', '0046_auto_20230427_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='has_sent_mail',
            field=models.BooleanField(default=False),
        ),
    ]
