# Generated by Django 2.2.24 on 2024-09-10 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("banquet", "0048_add_dietary_preferences"),
    ]

    operations = [
        migrations.CreateModel(
            name="DietaryPreference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("order", models.IntegerField(default=0)),
                (
                    "banquet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="banquet.Banquet",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.AlterField(
            model_name="participant",
            name="dietary_preference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="banquet.DietaryPreference",
            ),
        ),
    ]
