# Generated by Django 2.2.24 on 2024-09-10 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banquet', '0049_change_dietary_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='dietary_preference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banquet.DietaryPreference'),
        ),
    ]
