# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('event_start', models.DateTimeField()),
                ('event_end', models.DateTimeField()),
                ('capacity', models.IntegerField(blank=True, default=1, null=True)),
                ('needs_approval', models.BooleanField()),
                ('description', models.TextField(blank=True)),
                ('registration_open', models.DateTimeField()),
                ('registration_last_day', models.DateTimeField()),
                ('registration_last_day_cancel', models.DateTimeField()),
                ('roles', models.CharField(choices=[('App', 'Applikationsutvecklare'), ('AD', 'Art Director'), ('BD', 'Backend Developer'), ('BE', 'Bankett: Eventteknikkoordinator'), ('BIK', 'Bankett: Inrednings- och Inkopsgruppledare'), ('BL', 'Bankett: Logistikgruppledare'), ('BU', 'Bankett: Underhallningsgruppledare'), ('BH', 'Banquet Host'), ('BRM', 'Business Relations Manager'), ('CM', 'Campaign Manager'), ('CFH', 'Career Fair Host'), ('CFM', 'Career Fair Manager'), ('CW', 'Copywriter'), ('EH', 'Event Host'), ('EM', 'Event Manager'), ('EG', 'Eventgruppledare'), ('FR', 'Foretagsreception'), ('FL', 'Fotogruppledare'), ('FP', 'Framtida projektledare'), ('FU', 'Frontend-utvecklare'), ('GF', 'Grafisk formgivare'), ('HBRE', 'Head of Business Relations and Events'), ('HLCF', 'Head of Logistics and Career Fair'), ('HMCI', 'Head of Marketing, Communications and Internal Systems'), ('H', 'Host'), ('ISM', 'Internal Systems Manager'), ('IWM', 'IT-Web Manager'), ('KF', 'Kampanj: Filmskapare'), ('KO', 'Kampanjkoordinator'), ('LM', 'Logistics Manager'), ('LH', 'Lounge Host'), ('LG', 'Loungegruppledare'), ('MGL', 'Massgruppledare'), ('MAM', 'Mobile Application Manager'), ('P', 'Photographer'), ('PM', 'Project Manager'), ('PGM', 'Projektgruppsmedlem'), ('RM', 'Recruitment Manager'), ('RG', 'Representationsgruppledare'), ('RGL', 'Representationssittningsgruppledare'), ('RGB', 'Representationssittningsgruppledare Bankett'), ('SH', 'Sambandhelp'), ('SH', 'Service Host'), ('SGL', 'Servicegruppledare'), ('SLGL', 'Specialstyrkan: Logistikgruppledare'), ('STGL', 'Specialstyrkan: Teknikgruppledare'), ('SK', 'Sponskoordinator'), ('SSM', 'Sponsorship and Service Manager'), ('SU', 'Systemutvecklare'), ('TF', 'Task force'), ('TL', 'Team Leader'), ('URH', 'University Relations Host')], max_length=3)),
                ('make_event_public', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=75)),
                ('status', models.CharField(choices=[('A', 'Approved'), ('C', 'Canceled'), ('D', 'Declined'), ('S', 'Submitted')], max_length=3)),
                ('name', models.CharField(max_length=75)),
                ('mobile', models.IntegerField(blank=True, default=1, null=True)),
                ('allergies', models.CharField(max_length=75)),
                ('attending', models.BooleanField()),
            ],
        ),
    ]
