# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_auto_20180730_1515"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="allowed_groups",
        ),
        migrations.RemoveField(
            model_name="event",
            name="extra_field",
        ),
        migrations.RemoveField(
            model_name="event",
            name="fair",
        ),
        migrations.RemoveField(
            model_name="event",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="eventanswer",
            name="attendence",
        ),
        migrations.RemoveField(
            model_name="eventanswer",
            name="question",
        ),
        migrations.RemoveField(
            model_name="eventattendence",
            name="event",
        ),
        migrations.RemoveField(
            model_name="eventattendence",
            name="user",
        ),
        migrations.RemoveField(
            model_name="eventquestion",
            name="event",
        ),
        migrations.DeleteModel(
            name="Event",
        ),
        migrations.DeleteModel(
            name="EventAnswer",
        ),
        migrations.DeleteModel(
            name="EventAttendence",
        ),
        migrations.DeleteModel(
            name="EventQuestion",
        ),
    ]
