# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 21:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_auto_20160811_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='EventQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=256)),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='make_event_public',
            new_name='public_registration',
        ),
        migrations.RemoveField(
            model_name='event',
            name='needs_approval',
        ),
        migrations.RemoveField(
            model_name='event',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='eventattendence',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='eventattendence',
            name='attending',
        ),
        migrations.RemoveField(
            model_name='eventattendence',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='eventattendence',
            name='name',
        ),
        migrations.RemoveField(
            model_name='eventattendence',
            name='person',
        ),
        migrations.AddField(
            model_name='eventattendence',
            name='event',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventattendence',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventattendence',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('C', 'Canceled'), ('D', 'Declined'), ('S', 'Submitted')], default='S', max_length=3),
        ),
        migrations.AddField(
            model_name='eventquestion',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='eventanswer',
            name='attendence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventAttendence'),
        ),
        migrations.AddField(
            model_name='eventanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventQuestion'),
        ),
    ]
