# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20160914_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventquestion',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='public_registration',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_last_day_cancel',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='eventanswer',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventquestion',
            name='question_text',
            field=models.TextField(),
        ),
    ]
