# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-16 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_event_invitation_participant_team_teaminvitation_teammember"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["date_start", "name"]},
        ),
        migrations.AddField(
            model_name="event",
            name="open_for_signup",
            field=models.BooleanField(
                default=False, verbose_name="Event is currently open for sign up"
            ),
            preserve_default=False,
        ),
    ]
