# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 08:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20160915_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattendence',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
