# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('events', '0005_auto_20160915_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allowed_groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
