# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-16 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_auto_20180916_1618"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="attended",
            field=models.NullBooleanField(
                verbose_name="The participant showed up to the event"
            ),
        ),
    ]
