# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_participant_attended"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignupQuestion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("required", models.BooleanField()),
                ("type", models.CharField(max_length=255)),
                ("question", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="participant",
            name="email_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="participant",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="participant",
            name="phone_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
