# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0001_initial'),
        ('events', '0006_event_allowed_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fair',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fair.Fair'),
            preserve_default=False,
        ),
    ]
