# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_fair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
    ]
