# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_auto_20180918_1505"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignupQuestionAnswer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField()),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.Participant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="signupquestion",
            name="event",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="events.Event",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="signupquestion",
            name="type",
            field=models.CharField(
                choices=[
                    ("text_field", "Text Field"),
                    ("text_area", "Text Area"),
                    ("radio", "Single Choice"),
                    ("checkbox", "Multiple Choice"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="signupquestionanswer",
            name="signup_question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="events.SignupQuestion"
            ),
        ),
    ]
