# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_description_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='send_submission_mail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='submission_mail_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='submission_mail_subject',
            field=models.TextField(blank=True),
        ),
    ]
