# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import lib.image


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20161003_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='registration_last_day',
            new_name='registration_end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='registration_open',
            new_name='registration_start',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to=lib.image.path),
        ),
    ]
