# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0012_auto_20180927_2246"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="signup_complete",
            field=models.BooleanField(
                default=False, verbose_name="The participant has completed signup"
            ),
        ),
    ]
