# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20161007_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendence_approvement_required',
            field=models.BooleanField(default=True),
        ),
    ]
