# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0002_partner_tag'),
        ('events', '0013_auto_20161007_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, to='fair.Tag'),
        ),
    ]
