# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20161014_1936'),
        ('events', '0014_auto_20161012_2055'),
    ]

    operations = [
    ]
