# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_merge_20161018_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
