# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20181007_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantCheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(null=True, verbose_name='When the participant checked in at the event')),
            ],
        ),
        migrations.RemoveField(
            model_name='checkintoken',
            name='participant',
        ),
        migrations.AddField(
            model_name='participant',
            name='check_in_token',
            field=models.CharField(default='9lnh6if7yLsEzroGacSLH8CALDGD7c2t', max_length=32, unique=True),
        ),
        migrations.DeleteModel(
            name='CheckInToken',
        ),
        migrations.AddField(
            model_name='participantcheckin',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Participant'),
        ),
    ]
