# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0017_auto_20181008_2022"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="check_in_token",
            field=models.CharField(
                default="lMhSLeeJnfl0dmbk8cE9q0Rm5q7C02aU", max_length=32, unique=True
            ),
        ),
    ]
