# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Choose which groups in armada should be able to see and         attend this event. NOTE: No groups make the event accesible to all         ais-users.', to='auth.Group'),
        ),
    ]
