# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20161027_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='published',
            field=models.BooleanField(default=False, help_text='If the event should be published in the apps and on the website.'),
        ),
    ]
