# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0019_auto_20181009_1215"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="check_in_token",
            field=models.CharField(
                default=events.models.get_random_32_length_string,
                max_length=32,
                unique=True,
            ),
        ),
    ]
