# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-13 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0021_auto_20181012_1113"),
        ("events", "0018_auto_20181008_2155"),
    ]

    operations = []
