# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20161031_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='submission_mail_subject',
            field=models.CharField(blank=True, max_length=78),
        ),
    ]
