# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0022_merge_20181013_1426"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="check_in_token",
            field=models.CharField(
                default=events.models.get_random_32_length_string,
                max_length=32,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="participantcheckin",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                null=True,
                verbose_name="When the participant checked in at the event",
            ),
        ),
    ]
