# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_event_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='food',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
