# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20161106_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendence',
            name='submission_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
