# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0025_event_food"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="signupquestion",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="signupquestionanswer",
            options={"ordering": ["signup_question__pk"]},
        ),
    ]
