# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0026_auto_20181030_0801"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
