# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_event_external_signup_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='external_signup_url',
            field=models.URLField(blank=True),
        ),
    ]
