# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_auto_20161110_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendence',
            name='sent_email',
            field=models.BooleanField(default=False),
        ),
    ]
