# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-16 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_participant_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(default=100, verbose_name='Maximum number of participants'),
        ),
    ]
