# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-09-28 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_participant_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='swish_charge_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
