# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-22 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_participant_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=75, null=True, verbose_name='Contact e-mail'),
        ),
    ]
