# Generated by Django 2.2.24 on 2024-07-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0031_add_program_file_question_foreign_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_max_capacity",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Event max capacity"
            ),
        ),
    ]
