# Generated by Django 2.2.24 on 2024-09-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_add_registration_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
