# Generated by Django 2.2.24 on 2024-09-10 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0033_change_registration_end"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="requires_invitation",
        ),
    ]
