# Generated by Django 2.2.24 on 2024-10-08 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0034_remove_requires_invitation"),
        ("events", "0032_event_max_capacity"),
    ]

    operations = []
