# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 15:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('field_type', models.CharField(choices=[('text_field', 'Text field'), ('check_box', 'Check box'), ('text_area', 'Text area'), ('radio_buttons', 'Radio buttons'), ('select', 'Drop-down list'), ('file', 'File'), ('image', 'Image')], default='text_field', max_length=20)),
                ('position', models.IntegerField(default=0)),
                ('required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.CustomField')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldArgument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('position', models.IntegerField(default=0)),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.CustomField')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='customfield',
            name='extra_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.ExtraField'),
        ),
    ]
