version: '3.3'

services:
  web:
    build: .
    #volumes:
    #  - .:/usr/src/app/
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
    command: source ./entrypoint.sh

  db:
    image: postgis/postgis:13-3.3
    volumes:
      # - postgres_data:/var/lib/postgresql/data/ # Production Development
      - ./ais-developer-database.sql:/docker-entrypoint-initdb.d # Local Development
    environment:
      - POSTGRES_USER=ais_dev
      - POSTGRES_PASSWORD=ais_dev
      - POSTGRES_DB=ais_dev

volumes:
  postgres_data:
   
