version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/usr/src/app/
    ports:
      - 8080:8080
    env_file:
      - ./.env.local
    depends_on:
      - db
      - node
    command: python manage.py runserver 0.0.0.0:8080 --settings=local_settings

  db:
    image: postgis/postgis:10-2.5-alpine
    volumes:
      # - postgres_data:/var/lib/postgresql/data/ # Production Development
      - ./ais-developer-database.sql:/docker-entrypoint-initdb.d/init.sql # Local Development
    environment:
      - POSTGRES_USER=ais_dev
      - POSTGRES_PASSWORD=ais_dev
      - POSTGRES_DB=ais_dev

volumes:
  postgres_data:
   
