# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('html_article_text', models.CharField(default='', max_length=5000)),
                ('publication_date', models.DateTimeField()),
            ],
        ),
    ]
