# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import lib.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(blank=True, max_length=50)),
                ('ingress', models.TextField(default='', max_length=500)),
                ('html_article_text', models.TextField(default='', max_length=5000)),
                ('publication_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, upload_to=lib.image.UploadToDirUUID('news', 'image'))),
            ],
        ),
    ]
