# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 17:25
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='html_text',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='html_article_text',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
