# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-21 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='html_text',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='html_article_text',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
