# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import lib.image


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, upload_to=lib.image.UploadToDirUUID('news', 'image')),
        ),
    ]
