# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsarticle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='ingress',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='html_article_text',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
