# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsarticle_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='image',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='image_2x',
            field=models.ImageField(blank=True, upload_to='news/image/'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='image_2x_wide',
            field=models.ImageField(blank=True, upload_to='news/image/'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='image_3x',
            field=models.ImageField(blank=True, upload_to='news/image/', verbose_name='Regular image (4:3) ratio'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='image_3x_wide',
            field=models.ImageField(blank=True, upload_to='news/image/', verbose_name='Wide image (16:9) ratio'),
        ),
    ]
