# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import lib.image


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20170615_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='image_2x',
            field=models.ImageField(blank=True, upload_to=lib.image.UploadToDirUUID('news', 'image')),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='image_2x_wide',
            field=models.ImageField(blank=True, upload_to=lib.image.UploadToDirUUID('news', 'image')),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='image_3x',
            field=models.ImageField(blank=True, upload_to=lib.image.UploadToDirUUID('news', 'image'), verbose_name='Regular image (4:3) ratio'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='image_3x_wide',
            field=models.ImageField(blank=True, upload_to=lib.image.UploadToDirUUID('news', 'image'), verbose_name='Wide image (16:9) ratio'),
        ),
    ]
