# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-30 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import lib.image


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20170615_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, upload_to=lib.image.UploadToDirUUID('news', 'image')),
        ),
    ]
