# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-30 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newsarticle_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='image',
        ),
    ]
