#!/bin/bash
echo "Post-receive started"
unset GIT_INDEX_FILE
read oldrev newrev refname
branch=$(echo $refname | cut -d/ -f3)
DEPLOY_DIR=/home/deployment
git --work-tree=$DEPLOY_DIR/ais --git-dir=$DEPLOY_DIR/git checkout -f master
git --work-tree=$DEPLOY_DIR/ais --git-dir=$DEPLOY_DIR/git clean -fdx

ln -s $DEPLOY_DIR/secrets.py $DEPLOY_DIR/ais/ais/secrets.py

# Restart the uwsgi server
while read line
do
    kill -HUP $line
done <$DEPLOY_DIR/ais-master.pid

/bin/bash -c "
  . $DEPLOY_DIR/ais_venv/bin/activate;
  python $DEPLOY_DIR/ais/manage.py migrate;
  /bin/bash /home/deployment/ais/restart_uwsgi_server.sh
"
echo "Deployed the branch $branch"
echo "Post-receive finished"

