#!/bin/bash
echo "Post-receive started"
unset GIT_INDEX_FILE

DEPLOY_DIR=/home/deployment/
alias git="git --work-tree=$DEPLOY_DIR/ais --git-dir=$DEPLOY_DIR/git"

git checkout -f master
git clean -fdx
cp $DEPLOY_DIR/secrets.py $DEPLOY_DIR/ais/ais/

# Restart the uwsgi server
while read line
do
    kill -HUP $line
done <$DEPLOY_DIR/ais-master.pid

/bin/bash -c "
  . $DEPLOY_DIR/ais_venv/bin/activate;
  python $DEPLOY_DIR/ais/manage.py migrate;
"
echo "Post-receive finished"
