# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 16:45
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('fair', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('field_type', models.CharField(choices=[('text_field', 'Text field'), ('check_box', 'Check box'), ('text_area', 'Text area'), ('radio_buttons', 'Radio buttons'), ('select', 'Drop-down list'), ('file', 'File'), ('image', 'Image')], default='text_field', max_length=20)),
                ('position', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1000)),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.CustomField')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldArgument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('position', models.IntegerField(default=0)),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.CustomField')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('interview_date', models.CharField(blank=True, max_length=100, null=True)),
                ('interview_location', models.CharField(blank=True, max_length=100, null=True)),
                ('submission_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentApplicationComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('recruitment_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.RecruitmentApplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('interview_end_date', models.DateTimeField()),
                ('eligible_roles', models.IntegerField(default=3)),
                ('application_questions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_questions', to='recruitment.ExtraField')),
                ('fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fair.Fair')),
                ('interview_questions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.ExtraField')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(default='', max_length=300)),
                ('parent_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.Role')),
                ('permissions', models.ManyToManyField(to='auth.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='RoleApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('recruitment_application', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recruitment.RecruitmentApplication')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.Role')),
            ],
        ),
        migrations.AddField(
            model_name='recruitmentperiod',
            name='recruitable_roles',
            field=models.ManyToManyField(to='recruitment.Role'),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='delegated_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegated_role', to='recruitment.Role'),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='exhibitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='recommended_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.Role'),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='recruitment_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.RecruitmentPeriod'),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='superior_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superior_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customfield',
            name='extra_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.ExtraField'),
        ),
    ]
