# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 12:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        #('auth', '0008_group_is_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fair', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('field_type', models.CharField(choices=[('text_field', 'Text field'), ('check_box', 'Check box'), ('text_area', 'Text area'), ('radio_buttons', 'Radio buttons'), ('file', 'File'), ('image', 'Image')], default='text_field', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1000)),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.CustomField')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldArgument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.CustomField')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitableRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1)),
                ('interviewDate', models.CharField(blank=True, max_length=100, null=True)),
                ('interviewLocation', models.CharField(blank=True, max_length=100, null=True)),
                ('submissionDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('delegatedRole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegatedRole', to='recruitment.RecruitableRole')),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviewer', to=settings.AUTH_USER_MODEL)),
                ('recommendedRole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.RecruitableRole')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('extra_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.ExtraField')),
                ('fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fair.Fair')),
            ],
        ),
        migrations.CreateModel(
            name='RoleApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruitableRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.RecruitableRole')),
                ('recruitmentApplication', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recruitment.RecruitmentApplication')),
            ],
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='recruitmentPeriod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.RecruitmentPeriod'),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='superiorUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superiorUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitablerole',
            name='recruitment_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.RecruitmentPeriod'),
        ),
        migrations.AddField(
            model_name='recruitablerole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='extra_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.ExtraField'),
        ),
    ]
