# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 12:46
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentApplicationComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.RenameField(
            model_name='recruitmentapplication',
            old_name='interviewDate',
            new_name='interview_date',
        ),
        migrations.RenameField(
            model_name='recruitmentapplication',
            old_name='interviewLocation',
            new_name='interview_location',
        ),
        migrations.RenameField(
            model_name='recruitmentapplication',
            old_name='recommendedRole',
            new_name='recommended_role',
        ),
        migrations.RenameField(
            model_name='recruitmentapplication',
            old_name='recruitmentPeriod',
            new_name='recruitment_period',
        ),
        migrations.RenameField(
            model_name='recruitmentapplication',
            old_name='submissionDate',
            new_name='submission_date',
        ),
        migrations.RenameField(
            model_name='recruitmentperiod',
            old_name='extra_field',
            new_name='interview_questions',
        ),
        migrations.RenameField(
            model_name='roleapplication',
            old_name='recruitableRole',
            new_name='recruitable_role',
        ),
        migrations.RenameField(
            model_name='roleapplication',
            old_name='recruitmentApplication',
            new_name='recruitment_application',
        ),
        migrations.RemoveField(
            model_name='recruitmentapplication',
            name='delegatedRole',
        ),
        migrations.RemoveField(
            model_name='recruitmentapplication',
            name='superiorUser',
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='delegated_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegated_role', to='recruitment.RecruitableRole'),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='status',
            field=models.CharField(choices=[('undecided', 'Undecided'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='undecided', max_length=20),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='superior_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superior_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitmentperiod',
            name='application_questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_questions', to='recruitment.ExtraField'),
        ),
        migrations.AddField(
            model_name='recruitmentperiod',
            name='eligible_roles',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='recruitmentperiod',
            name='interview_end_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 6, 12, 46, 59, 415037, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roleapplication',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('text_field', 'Text field'), ('check_box', 'Check box'), ('text_area', 'Text area'), ('radio_buttons', 'Radio buttons'), ('select', 'Drop-down list'), ('file', 'File'), ('image', 'Image')], default='text_field', max_length=20),
        ),
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitmentapplicationcomment',
            name='recruitment_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.RecruitmentApplication'),
        ),
        migrations.AddField(
            model_name='recruitmentapplicationcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
