# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentperiod',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
