# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20160531_0848'),
        ('recruitment', '0002_auto_20160806_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentapplication',
            name='exhibitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
    ]
