# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_recruitmentperiod_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
