# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-19 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20160531_0848'),
        ('auth', '0010_remove_user_external'),
        ('recruitment', '0002_auto_20160806_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(default='', max_length=300)),
                ('parent_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.Role')),
                ('permissions', models.ManyToManyField(to='auth.Permission')),
            ],
        ),
        migrations.RemoveField(
            model_name='recruitablerole',
            name='recruitment_period',
        ),
        migrations.RemoveField(
            model_name='recruitablerole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='roleapplication',
            name='recruitable_role',
        ),
        migrations.AddField(
            model_name='customfield',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customfieldargument',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='exhibitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='delegated_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegated_role', to='recruitment.Role'),
        ),
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='recommended_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.Role'),
        ),
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='status',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='RecruitableRole',
        ),
        migrations.AddField(
            model_name='recruitmentperiod',
            name='recruitable_roles',
            field=models.ManyToManyField(to='recruitment.Role'),
        ),
        migrations.AddField(
            model_name='roleapplication',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recruitment.Role'),
            preserve_default=False,
        ),
    ]
