# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 16:00
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruitment', '0003_auto_20160403_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1)),
                ('submissionDate', models.DateField(blank=True, default=datetime.datetime.now)),
                ('recruitmentPeriod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.RecruitmentPeriod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoleApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='recruitablerole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='roleapplication',
            name='recruitableRole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.RecruitableRole'),
        ),
        migrations.AddField(
            model_name='roleapplication',
            name='recruitmentApplication',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recruitment.RecruitmentApplication'),
        ),
    ]
