# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0003_auto_20180819_1431"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recruitmentperiod",
            options={
                "ordering": ["fair", "name"],
                "permissions": (("administer_recruitment", "Administer recruitment"),),
            },
        ),
    ]
