# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_auto_20160820_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
