# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_auto_20180819_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['recruitment_period', 'organization_group', 'name'], 'permissions': (('administer_roles', 'Administer roles'),)},
        ),
    ]
