# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_auto_20160821_0229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='submission_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
