# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0007_location_slot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slot",
            name="end",
        ),
        migrations.AddField(
            model_name="slot",
            name="length",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
