# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_auto_20160822_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentapplicationcomment',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
