# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_role_rolepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitablerole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.Role'),
        ),
    ]
