# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_auto_20160808_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='parentRole',
            new_name='parent_role',
        ),
    ]
