# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_auto_20160826_2253'),
    ]

    operations = []
