# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recruitment", "0009_auto_20180830_1741"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="slot",
            options={"ordering": ["start", "location"]},
        ),
        migrations.AlterField(
            model_name="slot",
            name="length",
            field=models.PositiveIntegerField(verbose_name="Length (minutes)"),
        ),
    ]
