# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_auto_20160808_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='delegated_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegated_role', to='recruitment.Role'),
        ),
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='recommended_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.Role'),
        ),
    ]
