# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 19:10
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command


def load_fixture(apps, schema_editor):
    call_command('loaddata', *['--app', 'recruitment', 'initial_data.json'])

class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_auto_20160826_2253'),
    ]

    operations = [
        migrations.RunPython(load_fixture)
    ]
