# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0010_auto_20160809_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
