# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0010_auto_20160827_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfieldanswer',
            name='answer',
            field=models.CharField(max_length=3000),
        ),
    ]
