# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-28 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0011_auto_20160828_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfieldanswer',
            name='answer',
            field=models.TextField(),
        ),
    ]
