# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0011_auto_20180830_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['start', 'location', 'recruitment_period']},
        ),
        migrations.RemoveField(
            model_name='recruitmentperiod',
            name='interview_end_date',
        ),
    ]
