# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        #('auth', '0008_auto_20160809_1652'),
        ('recruitment', '0011_auto_20160809_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolepermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='role',
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(to='auth.Permission'),
        ),
        migrations.DeleteModel(
            name='RolePermission',
        ),
    ]
