# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recruitment", "0012_auto_20180830_2054"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recruitmentapplication",
            options={
                "ordering": ["submission_date"],
                "permissions": (
                    (
                        "administer_recruitment_applications",
                        "Administer recruitment applications",
                    ),
                    ("view_recruitment_applications", "View recruitment applications"),
                    ("view_recruitment_interviews", "View recruitment interviews"),
                ),
            },
        ),
        migrations.AlterModelOptions(
            name="recruitmentperiod",
            options={
                "ordering": ["fair", "start_date", "name"],
                "permissions": (("administer_recruitment", "Administer recruitment"),),
            },
        ),
    ]
