# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0012_auto_20160809_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitablerole',
            name='recruitment_period',
        ),
        migrations.RemoveField(
            model_name='recruitablerole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='roleapplication',
            name='recruitable_role',
        ),
        migrations.AddField(
            model_name='recruitmentperiod',
            name='recruitable_roles',
            field=models.ManyToManyField(to='recruitment.Role'),
        ),
        migrations.AddField(
            model_name='roleapplication',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recruitment.Role'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RecruitableRole',
        ),
    ]
