# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0013_auto_20160829_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitmentperiod',
            name='image',
        ),
    ]
