# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0014_remove_recruitmentperiod_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customfieldargument',
            name='value',
            field=models.TextField(),
        ),
    ]
