# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0014_remove_recruitmentapplication_exhibitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='allow_exhibitor_contact_person',
            field=models.BooleanField(default=False, verbose_name='People with this role can be contact persons for exhibitors'),
        ),
    ]
