# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 20:42
from __future__ import unicode_literals


from django.db import migrations
from django.core.management import call_command


def load_fixture(apps, schema_editor):
    call_command('loaddata', *['--app', 'recruitment', 'initial_data.json'])

class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0015_auto_20160830_0250'),
    ]

    operations = [
        migrations.RunPython(load_fixture)
    ]
