# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0015_role_allow_exhibitor_contact_person"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recruitmentapplication",
            options={
                "ordering": ["submission_date", "user"],
                "permissions": (
                    (
                        "administer_recruitment_applications",
                        "Administer recruitment applications",
                    ),
                    ("view_recruitment_applications", "View recruitment applications"),
                    ("view_recruitment_interviews", "View recruitment interviews"),
                ),
            },
        ),
    ]
