# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-01 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0016_auto_20180930_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruitmentapplication',
            options={'ordering': ['submission_date'], 'permissions': (('administer_recruitment_applications', 'Administer recruitment applications'), ('view_recruitment_applications', 'View recruitment applications'), ('view_recruitment_interviews', 'View recruitment interviews'))},
        ),
    ]
