# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0016_auto_20160831_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentapplicationcomment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
