# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recruitment", "0017_auto_20181001_1205"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={
                "ordering": ["recruitment_period", "name"],
                "permissions": (("administer_roles", "Administer roles"),),
            },
        ),
        migrations.RemoveField(
            model_name="role",
            name="organization_group",
        ),
    ]
