# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recruitment", "0019_auto_20181003_1223"),
        ("recruitment", "0013_auto_20180909_1636"),
    ]

    operations = []
