# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0019_role_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruitmentperiod',
            options={'permissions': (('administer_recruitment', 'Administer recruitment'),)},
        ),
    ]
