# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0020_auto_20160910_0055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruitmentapplication',
            options={'permissions': (('administer_recruitment_applications', 'Administer recruitment applications'), ('view_recruitment_applications', 'View recruitment applications'))},
        ),
    ]
