# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0022_auto_20160910_0104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'permissions': (('administer_roles', 'Administer roles'),)},
        ),
    ]
