# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-17 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0022_auto_20190817_1813"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitmentperiod",
            name="message_to_applicants",
            field=models.TextField(
                blank=True,
                help_text="If a message is given it will be displayed to the applicant in the application form before the Apply/Save button.",
                null=True,
            ),
        ),
    ]
