# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0023_auto_20160910_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.DeleteModel(
            name='AISPermission',
        ),
    ]
