# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0026_auto_20160919_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfield',
            name='extra_field',
        ),
        migrations.RemoveField(
            model_name='customfieldanswer',
            name='custom_field',
        ),
        migrations.RemoveField(
            model_name='customfieldanswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customfieldargument',
            name='custom_field',
        ),
        migrations.AlterField(
            model_name='recruitmentperiod',
            name='application_questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_questions', to='forms.ExtraField'),
        ),
        migrations.AlterField(
            model_name='recruitmentperiod',
            name='interview_questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.ExtraField'),
        ),
        migrations.DeleteModel(
            name='CustomField',
        ),
        migrations.DeleteModel(
            name='CustomFieldAnswer',
        ),
        migrations.DeleteModel(
            name='CustomFieldArgument',
        ),
        migrations.DeleteModel(
            name='ExtraField',
        ),
    ]
