# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0027_recruitmentapplication_scorecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentapplication',
            name='drive_document',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
