# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-05 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0028_recruitmentapplication_drive_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='organization_group',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
