# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 19:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruitment', '0029_role_organization_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentapplication',
            name='interviewer2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviewer2', to=settings.AUTH_USER_MODEL),
        ),
    ]
