# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('recruitment', '0030_recruitmentapplication_interviewer2'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentperiod',
            name='allowed_groups',
            field=models.ManyToManyField(help_text='Only those who are members of at least one of the selected groups can see the applications submitted to this recruitment period.', to='auth.Group'),
        ),
    ]
