# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0031_recruitmentperiod_allowed_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='_question_rendered',
            field=models.TextField(default='x', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customfield',
            name='question_markup_type',
            field=models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown')], default='markdown', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='question',
            field=markupfield.fields.MarkupField(rendered_field=True),
        ),
    ]
