# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0032_auto_20180413_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='status',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], max_length=20, null=True),
        ),
    ]
