# Generated by Django 2.2.24 on 2024-04-25 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=2024)),
                ('party_goers', models.ManyToManyField(blank=True, help_text='Fun people who like to party', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
