# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fair', '0004_auto_20170305_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contract', models.FileField(upload_to='contracts/%Y%m%d/')),
                ('current', models.BooleanField(default=False)),
                ('fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fair.Fair')),
            ],
        ),
    ]
