# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_auto_20170304_1648'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Contact')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.SignupContract')),
            ],
        ),
    ]
