# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signupcontract",
            name="type",
            field=models.CharField(
                choices=[("INITIAL", "Initial"), ("COMPLETE", "Complete")],
                default=("INITIAL", "Initial"),
                max_length=200,
            ),
        ),
    ]
