# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_signuplog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupcontract',
            name='contract',
            field=models.FileField(editable=False, upload_to='contracts/%Y%m%d/'),
        ),
    ]
