# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0022_auto_20170306_1828'),
        ('register', '0004_auto_20170305_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuplog',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
    ]
