# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_signuplog_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuplog',
            name='type',
            field=models.CharField(blank=True, choices=[('initial', 'Initial'), ('complete', 'Complete')], max_length=30, null=True),
        ),
    ]
