# Generated by Django 2.2.24 on 2024-02-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0005_auto_20190505_1539"),
    ]

    operations = [
        migrations.AddField(
            model_name="signuplog",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
