# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0005_fair_current'),
        ('companies', '0025_auto_20170410_1307'),
        ('register', '0006_signuplog_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(blank=True, choices=[('submit', 'Submitted'), ('save', 'Saved')], max_length=30, null=True)),
                ('products', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Contact')),
                ('fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fair.Fair')),
            ],
        ),
    ]
