# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20180406_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlog',
            name='company_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.CompanyContact'),
        ),
        migrations.AlterField(
            model_name='signuplog',
            name='company_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.CompanyContact'),
        ),
    ]
