# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20180406_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlog',
            name='company',
        ),
        migrations.RemoveField(
            model_name='orderlog',
            name='company_contact',
        ),
        migrations.RemoveField(
            model_name='orderlog',
            name='fair',
        ),
        migrations.DeleteModel(
            name='OrderLog',
        ),
    ]
