# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20180406_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuplog',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='companies.Company'),
        ),
    ]
