# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_auto_20180426_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signuplog',
            options={'ordering': ['-timestamp']},
        ),
    ]
