# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, null=True)),
                ('street_address', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TransportationOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuber_of_packages', models.IntegerField(default=0)),
                ('nuber_of_pallets', models.IntegerField(default=0)),
                ('goods_description', models.TextField(blank=True, max_length=250)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_phone_number', models.CharField(max_length=50)),
                ('delivery_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address', to='transportation.Address')),
                ('pickup_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_address', to='transportation.Address')),
            ],
        ),
    ]
