# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportationorder',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='transportationorder',
            name='pickup_address',
        ),
        migrations.AddField(
            model_name='transportationorder',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transportationorder',
            name='delivery_street_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transportationorder',
            name='delivery_zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='transportationorder',
            name='pickup_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transportationorder',
            name='pickup_street_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transportationorder',
            name='pickup_zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
