# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0027_invoicedetails'),
        ('transportation', '0002_auto_20180128_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportationorder',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
    ]
