# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0003_transportationorder_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportationorder',
            name='company',
        ),
    ]
