# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=64)),
                ('zip_code', models.CharField(max_length=8)),
                ('city', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=32)),
            ],
        ),
        migrations.RenameModel(
            old_name='CompanyParticipationYear',
            new_name='Exhibitor',
        ),
        migrations.AddField(
            model_name='company',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address', to='companies.Address'),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice__address', to='companies.Address'),
        ),
    ]
