# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20160920_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='invoice_address',
        ),
        migrations.AddField(
            model_name='company',
            name='delivery_address_city',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='company',
            name='delivery_address_country',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='company',
            name='delivery_address_street',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='company',
            name='delivery_address_zip_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_address_city',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_address_country',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_address_street',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_address_zip_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
