# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20180806_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='invoice_city',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_co',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_country',
            field=models.CharField(choices=[('DENMARK', 'Denmark'), ('FINLAND', 'Finland'), ('FRANCE', 'France'), ('GERMANY', 'Germany'), ('NORWAY', 'Norway'), ('SWEDEN', 'Sweden'), ('UNITED_KINGDOM', 'United Kingdom')], default='SWEDEN', max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_reference',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_street',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_zipcode',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
