# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20180814_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='invoice_co',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Invoice c/o'),
        ),
    ]
