# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_exhibitor_responsible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('cell_phone', models.CharField(max_length=50)),
                ('work_phone', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='companycontact',
            name='company',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='company',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='fair',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='responsible',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='delivery_address_city',
            new_name='address_city',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='delivery_address_country',
            new_name='address_country',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='delivery_address_street',
            new_name='address_street',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='delivery_address_zip_code',
            new_name='address_zip_code',
        ),
        migrations.RemoveField(
            model_name='company',
            name='invoice_address_city',
        ),
        migrations.RemoveField(
            model_name='company',
            name='invoice_address_country',
        ),
        migrations.RemoveField(
            model_name='company',
            name='invoice_address_street',
        ),
        migrations.RemoveField(
            model_name='company',
            name='invoice_address_zip_code',
        ),
        migrations.DeleteModel(
            name='CompanyContact',
        ),
        migrations.DeleteModel(
            name='Exhibitor',
        ),
        migrations.AddField(
            model_name='company',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Contact'),
        ),
    ]
