# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20180814_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name_legal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Legal organization name'),
        ),
    ]
