# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0006_company_name_legal"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="name_legal",
            new_name="invoice_name",
        ),
        migrations.AddField(
            model_name="company",
            name="ths_customer_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="THS Customer ID"
            ),
        ),
    ]
