# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20161010_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address_zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
