# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20161010_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(max_length=300),
        ),
    ]
