# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20180815_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='phone_number',
        ),
    ]
