# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_remove_company_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='invoice_country',
            field=models.CharField(blank=True, choices=[('DENMARK', 'Denmark'), ('FINLAND', 'Finland'), ('FRANCE', 'France'), ('GERMANY', 'Germany'), ('NORWAY', 'Norway'), ('SWEDEN', 'Sweden'), ('UNITED_KINGDOM', 'United Kingdom')], default='SWEDEN', max_length=200, null=True),
        ),
    ]
