# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_auto_20180815_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='invoice_street',
            new_name='invoice_address_line_1',
        ),
    ]
