# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_auto_20180815_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='invoice_co',
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_address_line_2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
