# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_auto_20161010_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address_city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_street',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_zip_code',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
