# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_auto_20161010_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='organisation_type',
            field=models.CharField(blank=True, choices=[('company', 'Company'), ('county_council', 'County/County council'), ('government_agency', 'Government agency'), ('non_profit_organisation', 'Non-profit organisation'), ('union', 'Union')], max_length=30, null=True),
        ),
    ]
