# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0011_auto_20180815_1428"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="invoice_address_line_3",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="invoice_email_address",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
