# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_contact_phone_switchboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='alternative_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
