# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_contact_alternative_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
