# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_auto_20161012_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to', to='companies.Company'),
        ),
    ]
