# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0017_auto_20180910_1920"),
    ]

    operations = [
        migrations.AddField(
            model_name="companycustomercomment",
            name="show_in_exhibitors",
            field=models.BooleanField(default=False),
        ),
    ]
