
# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 14:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def move_company_contact_connection(apps, schema_editor):
    Company = apps.get_model("companies", "Company")
    Contact = apps.get_model("companies", "Contact")
    db_alias = schema_editor.connection.alias
    companies = Company.objects.using(db_alias).all()
    for company in companies:
        if company.contact:
            company.contact.belongs_to = company
            company.contact.save()

def reverse_change():
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_contact_user'),
    ]

    operations = [
        migrations.RunPython(move_company_contact_connection, reverse_change),
    ]
