# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-01 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0019_auto_20180930_2206"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="allow_exhibitors",
            field=models.BooleanField(default=True),
        ),
    ]
