# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0017_auto_20180909_1636"),
        ("companies", "0022_companycontact_preferred_language"),
    ]

    operations = []
