# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_auto_20170306_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
