# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-28 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0024_company_show_externally"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="general_email_address",
            field=models.EmailField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="General e-mail address",
            ),
        ),
    ]
