# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0024_contact_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='belongs_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to', to='companies.Company'),
        ),
    ]
