# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-20 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0025_company_general_email_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="invoice_country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DENMARK", "Denmark"),
                    ("FINLAND", "Finland"),
                    ("FRANCE", "France"),
                    ("GERMANY", "Germany"),
                    ("NORWAY", "Norway"),
                    ("POLAND", "Poland"),
                    ("SWEDEN", "Sweden"),
                    ("UNITED_KINGDOM", "United Kingdom"),
                    ("NETHERLANDS", "Netherlands"),
                ],
                default="SWEDEN",
                max_length=200,
                null=True,
            ),
        ),
    ]
