# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def copy_invoice_info_from_exhibitor(apps, schema_editor):
    Exhibitor = apps.get_model('exhibitors', 'exhibitor')
    InvoiceDetails = apps.get_model('companies', 'invoicedetails')
    for exhibitor in Exhibitor.objects.all():
        company = exhibitor.company
        InvoiceDetails.objects.create(
                reference=exhibitor.invoice_reference,
                purchase_order_number=exhibitor.invoice_purchase_order_number,
                reference_phone_number=exhibitor.invoice_reference_phone_number,
                organisation_name = exhibitor.invoice_organisation_name,
                address = exhibitor.invoice_address,
                address_po_box = exhibitor.invoice_address_po_box,
                address_zip_code = exhibitor.invoice_address_zip_code,
                identification = exhibitor.invoice_identification,
                additional_information = exhibitor.invoice_additional_information,
                company = exhibitor.company
                )


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0026_company_related_programme'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('purchase_order_number', models.CharField(blank=True, max_length=200)),
                ('reference_phone_number', models.CharField(blank=True, max_length=200)),
                ('organisation_name', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('address_po_box', models.CharField(blank=True, max_length=200)),
                ('address_zip_code', models.CharField(blank=True, max_length=100)),
                ('identification', models.CharField(blank=True, max_length=200)),
                ('additional_information', models.CharField(blank=True, max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_details', to='companies.Company')),
            ],
        ),
        migrations.RunPython(copy_invoice_info_from_exhibitor, migrations.RunPython.noop)
    ]
