# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-11 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0026_auto_20190820_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='e_invoice',
            field=models.IntegerField(default=0, verbose_name='E-invoice'),
        ),
    ]
