# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0008_auto_20180110_1850'),
        ('companies', '0028_auto_20180324_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fair.Fair')),
            ],
            options={
                'ordering': ['fair', 'company'],
                'verbose_name_plural': 'Company customers',
            },
        ),
        migrations.CreateModel(
            name='CompanyCustomerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['status'],
                'verbose_name_plural': 'Company statuses',
            },
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['type'],
                'verbose_name_plural': 'Company types',
            },
        ),
        migrations.AddField(
            model_name='companycustomer',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.CompanyCustomerStatus'),
        ),
    ]
