# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0008_auto_20180110_1850'),
        ('companies', '0029_auto_20180403_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fair.Fair')),
            ],
            options={
                'verbose_name_plural': 'Groups',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='companycustomer',
            name='status',
        ),
        migrations.DeleteModel(
            name='CompanyCustomerStatus',
        ),
        migrations.AddField(
            model_name='companycustomer',
            name='group',
            field=models.ManyToManyField(to='companies.Group'),
        ),
    ]
