# Generated by Django 2.2.24 on 2023-08-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0029_auto_20210918_2247"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="invoice_email_address",
            field=models.EmailField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Invoice e-mail address",
            ),
        ),
    ]
