# Generated by Django 2.2.24 on 2023-08-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0030_auto_20230816_0013"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="invoice_country",
            field=models.CharField(
                blank=True, default="SWEDEN", max_length=200, null=True
            ),
        ),
    ]
