# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0031_group_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='abstract',
            field=models.BooleanField(default=False),
        ),
    ]
