# Generated by Django 2.2.24 on 2024-11-09 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0032_add_company_type_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'permissions': (('base', 'Companies'), ('host_representative', 'Can be host representative')), 'verbose_name_plural': 'Companies'},
        ),
    ]
