# Generated by Django 2.2.24 on 2024-06-14 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0033_companycustomerchat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companycustomerchat',
            old_name='comment',
            new_name='chat',
        ),
        migrations.RemoveField(
            model_name='companycustomerchat',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='companycustomerchat',
            name='show_in_exhibitors',
        ),
    ]
