# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0034_auto_20180403_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('street', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('reference', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(choices=[('INVOICE', 'Invoice'), ('TRANSPORT', 'Transport'), ('OFFICE', 'Office')], max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
            options={
                'verbose_name_plural': 'Company addresses',
                'ordering': ['company'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='group',
        ),
    ]
