# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0035_auto_20180403_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='revenue',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
