# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0036_auto_20180403_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyaddress',
            options={'verbose_name_plural': 'Company addresses'},
        ),
        migrations.AlterModelOptions(
            name='companycustomer',
            options={'verbose_name_plural': 'Company customers'},
        ),
    ]
