# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0037_auto_20180403_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('data', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['parent__name', 'name'], 'verbose_name_plural': 'Groups'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='additional_address_information',
        ),
        migrations.RemoveField(
            model_name='company',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='company',
            name='address_country',
        ),
        migrations.RemoveField(
            model_name='company',
            name='address_street',
        ),
        migrations.RemoveField(
            model_name='company',
            name='address_zip_code',
        ),
        migrations.RemoveField(
            model_name='company',
            name='organisation_type',
        ),
        migrations.RemoveField(
            model_name='company',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='companylog',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
    ]
