# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0008_auto_20180110_1850'),
        ('companies', '0038_auto_20180403_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylog',
            name='fair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fair.Fair'),
        ),
    ]
