# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0040_auto_20180403_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyaddress',
            old_name='email',
            new_name='email_address',
        ),
    ]
