# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0041_auto_20180403_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='identity_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
