# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0042_auto_20180403_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companylog',
            name='action',
        ),
    ]
