# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0008_auto_20180110_1850'),
        ('companies', '0043_remove_companylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaddress',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name, if different from the organisation name'),
        ),
        migrations.AlterUniqueTogether(
            name='companycustomer',
            unique_together=set([('company', 'fair')]),
        ),
    ]
