# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0044_auto_20180404_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companycustomer',
            old_name='group',
            new_name='groups',
        ),
    ]
