# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0045_auto_20180404_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.CompanyType'),
        ),
    ]
