# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0047_auto_20180404_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Organisation name'),
        ),
    ]
