# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0049_auto_20180405_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companycustomerresponsible',
            options={'ordering': ['company__name', 'user__name'], 'verbose_name_plural': 'Company customer responsibles'},
        ),
    ]
