# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 17:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0050_auto_20180405_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companycustomerresponsible',
            options={'ordering': ['company_customer__company__name', 'user__first_name', 'user__last_name'], 'verbose_name_plural': 'Company customer responsibles'},
        ),
        migrations.AlterUniqueTogether(
            name='companycustomerresponsible',
            unique_together=set([('company_customer', 'user')]),
        ),
    ]
