# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0051_auto_20180405_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='abstract',
            new_name='allow_responsibilities',
        ),
        migrations.AddField(
            model_name='group',
            name='allow_companies',
            field=models.BooleanField(default=True),
        ),
    ]
