# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0052_auto_20180405_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='allow_registration',
            field=models.BooleanField(default=True),
        ),
    ]
