# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 17:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0053_group_allow_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycustomerresponsible',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companycustomerresponsible',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='companycustomerresponsible',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='companycustomerresponsible',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='companycustomerresponsible',
            unique_together=set([('company_customer', 'group')]),
        ),
    ]
