# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0054_auto_20180405_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companycustomerresponsible',
            options={'ordering': ['company_customer__company__name', 'group__name'], 'verbose_name_plural': 'Company customer responsibles'},
        ),
    ]
