# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0055_auto_20180405_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=200)),
                ('alternative_email_address', models.EmailField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(max_length=200)),
                ('cell_phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('work_phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='belongs_to',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.AddField(
            model_name='company',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
