# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 10:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0056_auto_20180406_1215'),
        ('register', '0009_auto_20180406_1215'),
        ('exhibitors', '0082_auto_20180406_1215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AddField(
            model_name='companycontact',
            name='company',
            field=models.ForeignKey(null = True, blank = True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='user',
            field=models.ForeignKey(null = True, blank = True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
