# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0057_auto_20180406_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontact',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
    ]
