# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 10:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0058_auto_20180406_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontact',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
