# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0063_auto_20180406_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companycontact',
            old_name='cell_phone_number',
            new_name='mobile_phone_number',
        ),
    ]
