# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 20:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0064_auto_20180406_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCustomerComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('company_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.CompanyCustomer')),
            ],
        ),
        migrations.AlterModelOptions(
            name='companyaddress',
            options={'verbose_name_plural': 'Company addresses'},
        ),
        migrations.AddField(
            model_name='group',
            name='allow_comments',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companyaddress',
            name='email_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='E-mail address'),
        ),
        migrations.AlterField(
            model_name='companycontact',
            name='alternative_email_address',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Alternative e-mail address'),
        ),
        migrations.AlterField(
            model_name='companycontact',
            name='email_address',
            field=models.EmailField(max_length=200, verbose_name='E-mail address'),
        ),
        migrations.AddField(
            model_name='companycustomercomment',
            name='groups',
            field=models.ManyToManyField(blank=True, to='companies.Group'),
        ),
        migrations.AddField(
            model_name='companycustomercomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
