# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0065_auto_20180406_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companycustomercomment',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='companycontact',
            name='name',
        ),
        migrations.AddField(
            model_name='companycontact',
            name='first_name',
            field=models.CharField(max_length=200, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='last_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='companycontact',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
