# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0066_auto_20180407_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'permissions': (('base', 'Companies'),), 'verbose_name_plural': 'Companies'},
        ),
    ]
