# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0067_auto_20180407_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaddress',
            name='country',
            field=models.CharField(choices=[('DENMARK', 'Denmark'), ('FINLAND', 'Finland'), ('FRANCE', 'France'), ('GERMANY', 'Germany'), ('NORWAY', 'Norway'), ('SWEDEN', 'Sweden'), ('UNITED_KINGDOM', 'United Kingdom')], default='SWEDEN', max_length=200),
        ),
    ]
