# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0068_companyaddress_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='allow_registration',
            field=models.BooleanField(default=False),
        ),
    ]
