# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0069_auto_20180412_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name_full',
            field=models.CharField(default='X', editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
