# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0070_group_name_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='allow_statistics',
            field=models.BooleanField(default=False),
        ),
    ]
