# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_auto_20180426_2243'),
        ('companies', '0071_group_allow_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.SignupContract'),
        ),
    ]
