# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0072_group_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycustomer',
            name='main_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_group', to='companies.Group'),
        ),
    ]
