# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0074_group_allow_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycustomer',
            name='main_group',
        ),
        migrations.AddField(
            model_name='companycustomer',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='companies.Group'),
        ),
    ]
