# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0077_group_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='color',
            field=models.CharField(blank=True, choices=[('BLUE', 'Blue'), ('GREEN', 'Green'), ('RED', 'Red'), ('YELLOW', 'Yellow')], max_length=200, null=True),
        ),
    ]
