# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0078_auto_20180606_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycustomercomment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='companycustomerresponsible',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
        migrations.AlterField(
            model_name='companycustomercomment',
            name='company_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.CompanyCustomer'),
        ),
        migrations.AlterField(
            model_name='companycustomerresponsible',
            name='company_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.CompanyCustomer'),
        ),
    ]
