# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0080_auto_20180708_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companycustomerresponsible',
            options={'ordering': ['company__name', 'group__name'], 'verbose_name_plural': 'Company customer responsibles'},
        ),
        migrations.AddField(
            model_name='company',
            name='groups',
            field=models.ManyToManyField(to='companies.Group'),
        ),
    ]
