# Generated by Django 2.2.24 on 2021-09-18 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booleanans',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='choiceans',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='integerans',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='textans',
            options={'base_manager_name': 'objects'},
        ),
    ]
