# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0005_fair_current'),
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='category',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.RemoveField(
            model_name='question',
            name='fair',
        ),
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matching.Category'),
        ),
        migrations.AddField(
            model_name='survey',
            name='fair',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fair.Fair'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matching.Survey'),
        ),
    ]
