# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0005_fair_current'),
        ('matching', '0002_auto_20170629_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='fair',
        ),
        migrations.AddField(
            model_name='survey',
            name='fair',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fair.Fair'),
        ),
    ]
