# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_auto_20170629_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
    ]
