# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_auto_20170629_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['text']},
        ),
    ]
