# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_auto_20170629_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
