# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_survey_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ManyToManyField(to='matching.Category'),
        ),
    ]
