# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booleanans',
            name='ans',
            field=models.BooleanField(),
        ),
    ]
