# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_auto_20170629_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matching.Survey'),
        ),
    ]
