# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_auto_20170630_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='category',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ManyToManyField(to='matching.Survey'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
