# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0008_auto_20170630_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text='question text to be displayed'),
        ),
    ]
