# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0009_auto_20170630_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(blank=True, help_text='question text to be displayed', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'text'), ('select', 'select'), ('integer', 'integer'), ('boolean', 'boolean')], help_text='question text to be displayed', max_length=256),
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ManyToManyField(help_text='question survey foregin key', to='matching.Survey'),
        ),
    ]
