# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0010_auto_20170630_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'text'), ('select', 'select'), ('integer', 'integer'), ('boolean', 'boolean')], max_length=256),
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ManyToManyField(to='matching.Survey'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
    ]
