# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0011_auto_20170630_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='help_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
