# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0012_question_help_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
    ]
