# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0013_auto_20170702_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, choices=[('text', 'text'), ('select', 'select'), ('integer', 'integer'), ('boolean', 'boolean')], max_length=256, null=True),
        ),
    ]
