# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0014_auto_20170702_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceans',
            name='ans',
            field=models.IntegerField(blank=True, choices=[(None, '-------'), (1, 'Definitely Not'), (2, 'Probably Not'), (3, 'Maybe'), (4, 'Probably'), (5, 'Definitely')], null=True),
        ),
    ]
