# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0015_auto_20170702_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booleanans',
            name='ans',
            field=models.NullBooleanField(choices=[(True, 'yes'), (False, 'no')]),
        ),
    ]
