# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-15 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0016_auto_20170703_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textans',
            name='ans',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
