# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-15 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0006_auto_20170831_2211'),
        ('matching', '0017_auto_20170815_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentQuestionBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256)),
                ('question_type', models.CharField(choices=[('slider', 'slider'), ('grading', 'grading')], max_length=64)),
            ],
            options={
                'default_permissions': (),
                'verbose_name': 'question',
            },
        ),
        migrations.CreateModel(
            name='StudentQuestionGrading',
            fields=[
                ('studentquestionbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='matching.StudentQuestionBase')),
            ],
            options={
                'default_permissions': (),
                'verbose_name': 'grading question',
            },
            bases=('matching.studentquestionbase',),
        ),
        migrations.CreateModel(
            name='StudentQuestionSlider',
            fields=[
                ('studentquestionbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='matching.StudentQuestionBase')),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('step', models.FloatField(blank=True, default=1.0, null=True)),
            ],
            options={
                'default_permissions': (),
                'verbose_name': 'slider question',
            },
            bases=('matching.studentquestionbase',),
        ),
        migrations.AddField(
            model_name='studentquestionbase',
            name='fair',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fair.Fair'),
        ),
    ]
