# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-16 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_profiles', '0002_auto_20170930_1718'),
        ('matching', '0018_auto_20171015_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswerBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'answer_base',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='WorkField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_field', models.TextField()),
            ],
            options={
                'verbose_name': 'work field',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='WorkFieldArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_area', models.TextField()),
            ],
            options={
                'verbose_name': 'work_field_area',
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='studentquestionbase',
            name='fair',
        ),
        migrations.AddField(
            model_name='studentquestionbase',
            name='survey',
            field=models.ManyToManyField(to='matching.Survey'),
        ),
        migrations.AddField(
            model_name='studentquestiongrading',
            name='grading_size',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='studentquestionslider',
            name='step',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StudentAnswerGrading',
            fields=[
                ('studentanswerbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='matching.StudentAnswerBase')),
                ('answer', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.StudentQuestionGrading')),
            ],
            options={
                'verbose_name': 'answer_grading',
                'default_permissions': (),
            },
            bases=('matching.studentanswerbase',),
        ),
        migrations.CreateModel(
            name='StudentAnswerSlider',
            fields=[
                ('studentanswerbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='matching.StudentAnswerBase')),
                ('answer', models.FloatField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.StudentQuestionSlider')),
            ],
            options={
                'verbose_name': 'answer_slider',
                'default_permissions': (),
            },
            bases=('matching.studentanswerbase',),
        ),
        migrations.CreateModel(
            name='StudentAnswerWorkField',
            fields=[
                ('studentanswerbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='matching.StudentAnswerBase')),
                ('answer', models.BooleanField(choices=[(True, 'yes'), (False, 'no')])),
            ],
            options={
                'verbose_name': 'answer_workfield',
                'default_permissions': (),
            },
            bases=('matching.studentanswerbase',),
        ),
        migrations.AddField(
            model_name='workfield',
            name='work_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matching.WorkFieldArea'),
        ),
        migrations.AddField(
            model_name='studentanswerbase',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profiles.StudentProfile'),
        ),
        migrations.AddField(
            model_name='studentanswerworkfield',
            name='work_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.WorkField'),
        ),
    ]
