# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-17 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0006_auto_20170831_2211'),
        ('matching', '0021_auto_20171016_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswerbase',
            name='fair',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fair.Fair'),
        ),
        migrations.AddField(
            model_name='studentanswerbase',
            name='survey',
            field=models.ManyToManyField(blank=True, to='matching.Survey'),
        ),
        migrations.AddField(
            model_name='studentquestionbase',
            name='fair',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fair.Fair'),
        ),
    ]
