# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-17 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0022_auto_20171017_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquestionbase',
            name='company_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matching.Question'),
        ),
    ]
