# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0062_auto_20171012_1910'),
        ('matching', '0022_auto_20171017_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('exhibitor', models.ManyToManyField(to='exhibitors.Exhibitor')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswerContinent',
            fields=[
                ('studentanswerbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='matching.StudentAnswerBase')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.Continent')),
            ],
            bases=('matching.studentanswerbase',),
        ),
        migrations.CreateModel(
            name='StudentAnswerRegion',
            fields=[
                ('studentanswerbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='matching.StudentAnswerBase')),
            ],
            bases=('matching.studentanswerbase',),
        ),
        migrations.CreateModel(
            name='SwedenCities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(unique=True)),
                ('exhibitor', models.ManyToManyField(to='exhibitors.Exhibitor')),
            ],
        ),
        migrations.CreateModel(
            name='SwedenRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.Survey')),
            ],
        ),
        migrations.AddField(
            model_name='swedencities',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.SwedenRegion'),
        ),
        migrations.AddField(
            model_name='studentanswerregion',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.SwedenRegion'),
        ),
    ]
