# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0023_auto_20171023_2319'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SwedenCities',
            new_name='SwedenCity',
        ),
    ]
