# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-17 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0023_studentquestionbase_company_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswerbase',
            name='fair',
        ),
        migrations.RemoveField(
            model_name='studentquestionbase',
            name='fair',
        ),
    ]
