# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-19 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0024_auto_20171017_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentquestionslider',
            name='step',
        ),
        migrations.AddField(
            model_name='studentquestionslider',
            name='logarithmic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentquestionslider',
            name='units',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
