# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0062_auto_20171012_1910'),
        ('matching', '0024_auto_20171019_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('exhibitor', models.ManyToManyField(to='exhibitors.Exhibitor')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswerContinent',
            fields=[
                ('studentanswerbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='matching.StudentAnswerBase')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.Continent')),
            ],
            bases=('matching.studentanswerbase',),
        ),
        migrations.AddField(
            model_name='workfield',
            name='exhibitor',
            field=models.ManyToManyField(to='exhibitors.Exhibitor'),
        ),
    ]
