# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0024_auto_20171024_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentanswercontinent',
            options={'verbose_name': 'answer_continent'},
        ),
        migrations.AlterModelOptions(
            name='studentanswerregion',
            options={'verbose_name': 'answer_region'},
        ),
        migrations.AlterModelOptions(
            name='swedencity',
            options={'verbose_name': 'Sweden cities'},
        ),
        migrations.RenameField(
            model_name='continent',
            old_name='name',
            new_name='continent',
        ),
    ]
