# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-19 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0025_auto_20171019_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentanswerbase',
            options={'default_permissions': (), 'verbose_name': 'answer base'},
        ),
        migrations.AlterModelOptions(
            name='studentanswergrading',
            options={'default_permissions': (), 'verbose_name': 'answer grading'},
        ),
        migrations.AlterModelOptions(
            name='studentanswerslider',
            options={'default_permissions': (), 'verbose_name': 'answer slider'},
        ),
        migrations.RenameField(
            model_name='studentanswerslider',
            old_name='answer',
            new_name='answer_max',
        ),
        migrations.AddField(
            model_name='studentanswerslider',
            name='answer_min',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
