# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0026_auto_20171024_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swedencity',
            options={'verbose_name': 'sweden cities'},
        ),
        migrations.RenameField(
            model_name='continent',
            old_name='continent',
            new_name='name',
        ),
    ]
