# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0027_auto_20171024_1311'),
        ('matching', '0024_auto_20171017_1513'),
    ]

    operations = [
    ]
