# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0028_merge_20171024_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentanswercontinent',
            options={'verbose_name': 'answer continent'},
        ),
        migrations.AlterModelOptions(
            name='studentanswerregion',
            options={'verbose_name': 'answer region'},
        ),
        migrations.AlterModelOptions(
            name='swedencity',
            options={'verbose_name': 'sweden city', 'verbose_name_plural': 'sweden cities'},
        ),
    ]
