# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-29 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0064_exhibitor_location_at_fair'),
        ('matching', '0029_auto_20171025_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='workfield',
            name='exhibitor',
            field=models.ManyToManyField(to='exhibitors.Exhibitor'),
        ),
    ]
