# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-27 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0029_auto_20171025_1458'),
        ('matching', '0026_auto_20171019_1838'),
    ]

    operations = [
    ]
