# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0031_auto_20171029_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswerslider',
            name='answer_min',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='studentanswerworkfield',
            name='answer',
            field=models.BooleanField(choices=[(True, 'yes'), (False, 'no')], default=False),
        ),
        migrations.AlterField(
            model_name='studentquestionslider',
            name='units',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
