# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def add_regions(apps, schema_editor):
    Region = apps.get_model('matching', 'Region')
    Region.objects.create(name='Africa', region_id=1)
    Region.objects.create(name='Asia' , region_id=2)
    Region.objects.create(name='Australia', region_id=3)
    Region.objects.create(name='Europe', region_id=4)
    Region.objects.create(name='North America', region_id=5)
    Region.objects.create(name='South America', region_id=6)
    Region.objects.create(name='Stockholm', region_id=7)
    Region.objects.create(name='Göteborg', region_id=8)
    Region.objects.create(name='Malmö', region_id=9)
    Region.objects.create(name='Norra Norrland', region_id=10)
    Region.objects.create(name='Östra Svealand', region_id=11)
    Region.objects.create(name='Södra Norrland', region_id=12)
    Region.objects.create(name='Mälardalen', region_id=13)
    Region.objects.create(name='Västra Svealand', region_id=14)
    Region.objects.create(name='Södra Sverige', region_id=15)

    JobType = apps.get_model('matching', 'JobType')
    JobType.objects.create(job_type='master thesis', job_type_id=1)
    JobType.objects.create(job_type='part time job', job_type_id=2)
    JobType.objects.create(job_type='trainee', job_type_id=3)
    JobType.objects.create(job_type='summer job', job_type_id=4)

class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0031_auto_20171030_1602'),
    ]

    operations = [
    	migrations.RunPython(add_regions),
    ]

