# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0071_auto_20171030_2040'),
        ('matching', '0031_auto_20171030_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='continent',
            name='exhibitor',
        ),
        migrations.AddField(
            model_name='continent',
            name='continent_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='continent',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matching.Survey'),
        ),
        migrations.AddField(
            model_name='swedenregion',
            name='region_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='swedenregion',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matching.Survey'),
        ),
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.Continent'),
        ),
        migrations.AddField(
            model_name='country',
            name='exhibitor',
            field=models.ManyToManyField(to='exhibitors.Exhibitor'),
        ),
    ]
