# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-02 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0035_add_jobtypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtype',
            name='exhibitor_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matching.Question'),
        ),
    ]
