# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-02 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0036_jobtype_exhibitor_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='relates_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matching.Survey'),
        ),
    ]
