# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-05 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0038_auto_20171102_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentanswercontinent',
            options={'verbose_name': 'answer continent', 'verbose_name_plural': 'answers continent'},
        ),
        migrations.AlterModelOptions(
            name='studentanswerjobtype',
            options={'verbose_name': 'answer job type', 'verbose_name_plural': 'answers job type'},
        ),
        migrations.AlterModelOptions(
            name='studentanswerregion',
            options={'verbose_name': 'answer region', 'verbose_name_plural': 'answers region'},
        ),
        migrations.AlterModelOptions(
            name='studentanswerworkfield',
            options={'default_permissions': (), 'verbose_name': 'answer work field', 'verbose_name_plural': 'answers work field'},
        ),
        migrations.AlterModelOptions(
            name='studentquestiongrading',
            options={'default_permissions': (), 'verbose_name': 'question grading', 'verbose_name_plural': 'questions grading'},
        ),
        migrations.AlterModelOptions(
            name='studentquestionslider',
            options={'default_permissions': (), 'verbose_name': 'question slider', 'verbose_name_plural': 'questions slider'},
        ),
        migrations.AlterModelOptions(
            name='workfield',
            options={'default_permissions': ()},
        ),
        migrations.RemoveField(
            model_name='studentanswerworkfield',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='continent',
            name='survey',
        ),
        migrations.AddField(
            model_name='continent',
            name='survey',
            field=models.ManyToManyField(null=True, to='matching.Survey'),
        ),
        migrations.RemoveField(
            model_name='swedencity',
            name='region',
        ),
        migrations.AddField(
            model_name='swedencity',
            name='region',
            field=models.ManyToManyField(to='matching.SwedenRegion'),
        ),
        migrations.RemoveField(
            model_name='swedenregion',
            name='survey',
        ),
        migrations.AddField(
            model_name='swedenregion',
            name='survey',
            field=models.ManyToManyField(null=True, to='matching.Survey'),
        ),
    ]
