# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def forwards_func(apps, schema_editor):
    Answer = apps.get_model('matching', 'answer')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    new_ct = ContentType.objects.get_for_model(Answer)
    Answer.objects.filter(polymorphic_ctype__isnull=True).update(polymorphic_ctype=new_ct)


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('matching', '0039_question_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'answer', 'verbose_name_plural': 'answers'},
        ),
        migrations.AddField(
            model_name='answer',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_matching.answer_set+', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.Response'),
        ),
        migrations.AlterField(
            model_name='booleanans',
            name='ans',
            field=models.NullBooleanField(choices=[(True, 'yes'), (False, 'no')], default=None),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
