# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0040_auto_20180119_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
    ]
