# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-06 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0040_workfield_exhibitors'),
        ('matching', '0039_auto_20171105_0228'),
    ]

    operations = [
    ]
