# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-08 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0071_auto_20171030_2040'),
        ('matching', '0043_auto_20171106_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='KNNClassifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('space_dim', models.IntegerField(default=0)),
                ('max_abs_value', models.FloatField(default=1.0)),
                ('norm_type', models.CharField(choices=[('euclidian', 'Euclidian'), ('lebesgue_1', 'Lebesgue p=1')], default='euclidian', max_length=128)),
                ('space_dict', models.CharField(blank=True, max_length=256, null=True)),
                ('current', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('survey', models.ManyToManyField(blank=True, to='matching.Survey')),
            ],
            options={
                'verbose_name': 'KNN Classifier',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='VectorKNN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('vector', models.CharField(max_length=128)),
                ('classifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.KNNClassifier')),
                ('exhibitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibitors.Exhibitor')),
            ],
            options={
                'verbose_name': 'KNN Vector',
            },
        ),
    ]
