# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-08 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0044_knnclassifier_vectorknn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knnclassifier',
            name='survey',
        ),
        migrations.AddField(
            model_name='knnclassifier',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matching.Survey'),
        ),
    ]
