# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-08 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0046_auto_20171108_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knnclassifier',
            name='space_dict',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
