# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-08 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0047_auto_20171109_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knnclassifier',
            name='space_dict',
            field=models.CharField(blank=True, max_length=1028, null=True),
        ),
        migrations.AlterField(
            model_name='vectorknn',
            name='vector',
            field=models.CharField(max_length=256),
        ),
    ]
