# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

