# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-19 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shirt_size',
            field=models.CharField(blank=True, choices=[('WXS', 'Woman X-Small'), ('WS', 'Woman Small'), ('WM', 'Woman Medium'), ('WL', 'Woman Large'), ('WXL', 'Woman X-Large'), ('MXS', 'Man X-Small'), ('MS', 'Man Small'), ('MM', 'Man Medium'), ('ML', 'Man Large'), ('MXL', 'Man X-Large')], max_length=3),
        ),
    ]
