# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-28 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20180828_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='short',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
