# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_profile_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
