# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_language_short'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='allergy',
        ),
        migrations.AddField(
            model_name='profile',
            name='no_dietary_restrictions',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='dietary_restrictions',
            field=models.ManyToManyField(to='people.DietaryRestriction'),
        ),
    ]
