# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0005_auto_20180918_1321"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="dietary_restrictions",
            field=models.ManyToManyField(blank=True, to="people.DietaryRestriction"),
        ),
    ]
