# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-01 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20180918_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kth_synchronize',
            field=models.BooleanField(default=True, verbose_name='Synchronize account data with KTH'),
        ),
    ]
