# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0008_auto_20181003_0934"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="programme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="people.Programme",
                verbose_name="Program",
            ),
        ),
    ]
