# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0009_auto_20181003_0935"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"permissions": [("base", "People")]},
        ),
    ]
