# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-28 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_profile_portrait'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='portrait',
        ),
    ]
