# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0010_auto_20181003_0938"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="drivers_license",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="shirt_size",
        ),
        migrations.AlterField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date of birth"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True, verbose_name="Linkedin URL"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="slack_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Slack ID"
            ),
        ),
    ]
