# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_profile_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
