# Generated by Django 2.2.24 on 2023-04-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0012_profile_other_dietary_restrictions"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="armada_email",
            field=models.EmailField(
                blank=True, max_length=75, null=True, verbose_name="E-mail address"
            ),
        ),
    ]
