# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_auto_20180412_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=255, null=True),
        ),
    ]
