# Generated by Django 2.2.24 on 2024-09-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_add_dietary_preferences'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DietaryPreference',
        ),
    ]
