# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_auto_20180412_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='shortening',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
