# Generated by Django 2.2.24 on 2024-10-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_remove_dietary_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietaryrestriction',
            name='show_in_banquet',
            field=models.BooleanField(default=True),
        ),
    ]
