# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_programme_shortening'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slack_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
