# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fair', '0001_initial'),
        ('people', '0007_auto_20160910_0109'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=64)),
                ('slug', models.SlugField(db_index=False)),
                ('short_description', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('employees_sweden', models.IntegerField()),
                ('employees_world', models.IntegerField()),
                ('countries', models.IntegerField()),
                ('website_url', models.CharField(blank=True, max_length=128)),
                ('facebook_url', models.CharField(blank=True, max_length=128)),
                ('twitter_url', models.CharField(blank=True, max_length=128)),
                ('linkedin_url', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fair.Fair')),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='WorkField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='cataloginfo',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exhibitors.Exhibitor'),
        ),
        migrations.AddField(
            model_name='cataloginfo',
            name='job_types',
            field=models.ManyToManyField(blank=True, to='exhibitors.JobType'),
        ),
        migrations.AddField(
            model_name='cataloginfo',
            name='main_work_field',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='exhibitors.WorkField'),
        ),
        migrations.AddField(
            model_name='cataloginfo',
            name='programs',
            field=models.ManyToManyField(blank=True, to='people.Programme'),
        ),
        migrations.AddField(
            model_name='cataloginfo',
            name='work_fields',
            field=models.ManyToManyField(blank=True, related_name='_cataloginfo_work_fields_+', to='exhibitors.WorkField'),
        ),
    ]
