# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cataloginfo',
            name='ad',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='cataloginfo',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='cataloginfo',
            name='logo_small',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
