# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exhibitors', '0001_initial'),
        ('people', '0001_initial'),
        ('fair', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cataloginfo',
            name='programs',
            field=models.ManyToManyField(blank=True, to='people.Programme'),
        ),
        migrations.AddField(
            model_name='cataloginfo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='fair.Tag'),
        ),
        migrations.AddField(
            model_name='cataloginfo',
            name='values',
            field=models.ManyToManyField(blank=True, to='exhibitors.Value'),
        ),
        migrations.AddField(
            model_name='cataloginfo',
            name='work_fields',
            field=models.ManyToManyField(blank=True, related_name='_cataloginfo_work_fields_+', to='exhibitors.WorkField'),
        ),
    ]
