# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 09:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0005_auto_20161006_1147'),
        ('exhibitors', '0001_squashed_0004_auto_20160921_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cataloginfo',
            name='id',
        ),
        migrations.AddField(
            model_name='cataloginfo',
            name='continents',
            field=models.ManyToManyField(blank=True, to='exhibitors.Continent'),
        ),
        migrations.AddField(
            model_name='cataloginfo',
            name='values',
            field=models.ManyToManyField(blank=True, to='exhibitors.Value'),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Contact'),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='hosts',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='invoice_address',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='invoice_address_city',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='invoice_address_country',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='invoice_address_zip_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='invoice_identification',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='cataloginfo',
            name='ad',
            field=models.ImageField(blank=True, upload_to=lib.image.path),
        ),
        migrations.AlterField(
            model_name='cataloginfo',
            name='countries',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cataloginfo',
            name='employees_sweden',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cataloginfo',
            name='employees_world',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cataloginfo',
            name='exhibitor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='exhibitors.Exhibitor'),
        ),
        migrations.AlterField(
            model_name='cataloginfo',
            name='logo',
            field=models.ImageField(blank=True, upload_to=lib.image.path),
        ),
        migrations.AlterField(
            model_name='cataloginfo',
            name='logo_small',
            field=models.ImageField(blank=True, upload_to=lib.image.path),
        ),
    ]
