# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-05 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibitors", "0002_auto_20180730_1515"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibitor",
            name="electricity_equipment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exhibitor",
            name="electricity_socket_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exhibitor",
            name="electricity_total_power",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
