# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0002_auto_20161004_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='exhibitors.ExhibitorLocation'),
        ),
    ]
