# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import lib.image


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0002_auto_20161006_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='cataloginfo',
            name='ad_original',
            field=models.ImageField(blank=True, upload_to=lib.image.UploadToDirUUID('exhibitors', 'ad')),
        ),
        migrations.AddField(
            model_name='cataloginfo',
            name='logo_original',
            field=models.ImageField(blank=True, upload_to=lib.image.UploadToDirUUID('exhibitors', 'logo_original')),
        ),
        migrations.AlterField(
            model_name='cataloginfo',
            name='ad',
            field=models.ImageField(blank=True, upload_to=lib.image.UploadToDir('exhibitors', 'ad')),
        ),
        migrations.AlterField(
            model_name='cataloginfo',
            name='logo',
            field=models.ImageField(blank=True, upload_to=lib.image.UploadToDir('exhibitors', 'logo')),
        ),
        migrations.AlterField(
            model_name='cataloginfo',
            name='logo_small',
            field=models.ImageField(blank=True, upload_to=lib.image.UploadToDir('exhibitors', 'logo_small')),
        ),
    ]
