# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-06 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exhibitors", "0003_auto_20180806_0022"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exhibitor",
            name="electricity_equipment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description of equipment"
            ),
        ),
        migrations.AlterField(
            model_name="exhibitor",
            name="electricity_socket_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Number of sockets"
            ),
        ),
        migrations.AlterField(
            model_name="exhibitor",
            name="electricity_total_power",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Estimated power consumption (W)"
            ),
        ),
    ]
