# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0003_auto_20160921_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cataloginfo',
            old_name='company',
            new_name='exhibitor',
        ),
    ]
