# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibitors", "0005_auto_20180814_1235"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exhibitor",
            name="placement_wish",
            field=models.CharField(
                choices=[
                    ("NO_WISH", "No wish"),
                    ("MIXED", "Mixed with companies from other industries"),
                    ("SIMILAR", "Next to similar companies"),
                ],
                default="NO_WISH",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
