# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0006_auto_20180814_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='booth_height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Height of the booth (cm)'),
        ),
    ]
