# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0006_auto_20161010_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitor',
            name='invoice_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='exhibitor',
            name='invoice_address_city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='exhibitor',
            name='invoice_address_country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='exhibitor',
            name='invoice_identification',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
