# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0008_auto_20180814_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitor',
            name='placement_wish',
            field=models.CharField(blank=True, choices=[('MIXED', 'Mixed with companies from other industries'), ('SIMILAR', 'Next to similar companies')], max_length=255, null=True),
        ),
    ]
