# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0009_auto_20161010_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='status',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('registered', 'Registered'), ('complete_registration', 'Complete registration'), ('contacted_by_host', 'Contacted by host'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked in'), ('checked_out', 'Checked out')], max_length=30, null=True),
        ),
    ]
