# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import lib.image


class Migration(migrations.Migration):

    dependencies = [
        ("exhibitors", "0010_auto_20180814_1406"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibitor",
            name="catalogue_logo_freesize",
            field=models.ImageField(
                blank=True,
                upload_to=lib.image.UploadToDirUUID(
                    "exhibitors", "catalogue_logo_freesize"
                ),
            ),
        ),
        migrations.AddField(
            model_name="exhibitor",
            name="catalogue_logo_squared",
            field=models.ImageField(
                blank=True,
                upload_to=lib.image.UploadToDirUUID(
                    "exhibitors", "catalogue_logo_squared"
                ),
            ),
        ),
    ]
