# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0010_exhibitor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
