# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0012_exhibitor_requests_for_stand_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='heavy_duty_electric_equipment',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
