# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0013_exhibitor_heavy_duty_electric_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='other_information_about_the_stand',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
