# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-22 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0014_auto_20180911_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cataloginfo',
            name='continents',
        ),
        migrations.RemoveField(
            model_name='cataloginfo',
            name='exhibitor',
        ),
        migrations.RemoveField(
            model_name='cataloginfo',
            name='job_types',
        ),
        migrations.RemoveField(
            model_name='cataloginfo',
            name='main_work_field',
        ),
        migrations.RemoveField(
            model_name='cataloginfo',
            name='programs',
        ),
        migrations.RemoveField(
            model_name='cataloginfo',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='cataloginfo',
            name='values',
        ),
        migrations.RemoveField(
            model_name='cataloginfo',
            name='work_fields',
        ),
        migrations.DeleteModel(
            name='CatalogInfo',
        ),
        migrations.DeleteModel(
            name='Continent',
        ),
        migrations.DeleteModel(
            name='Value',
        ),
        migrations.DeleteModel(
            name='WorkField',
        ),
    ]
