# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0014_exhibitor_other_information_about_the_stand'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='transport_to_fair_type',
            field=models.CharField(blank=True, choices=[('external_delivery', 'Yes, with an external delivery firm'), ('arkad_delivery', 'Yes, with transport from Arkad in Lund'), ('self_delivery', 'No, we will bring our goods ourselves')], max_length=30, null=True),
        ),
    ]
