# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0015_exhibitor_transport_to_fair_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='number_of_packages_from_fair',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='number_of_packages_to_fair',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='number_of_pallets_from_fair',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='number_of_pallets_to_fair',
            field=models.IntegerField(default=0),
        ),
    ]
