# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-22 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0006_auto_20180918_1327"),
        ("exhibitors", "0016_auto_20180922_1650"),
    ]

    operations = [
        migrations.AddField(
            model_name="lunchticket",
            name="dietary_restrictions",
            field=models.ManyToManyField(blank=True, to="people.DietaryRestriction"),
        ),
    ]
