# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0016_auto_20161012_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitor',
            name='transport_to_fair_type',
            field=models.CharField(blank=True, choices=[('external_transport', 'Yes, with an external delivery firm'), ('arkad_transport', 'Yes, with transport from Arkad in Lund'), ('self_transport', 'No, we will bring our goods ourselves')], max_length=30, null=True),
        ),
    ]
