# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-22 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0017_lunchticket_dietary_restrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchticket',
            name='email_address',
            field=models.CharField(default='no@email.com', max_length=255, verbose_name='E-mail address'),
            preserve_default=False,
        ),
    ]
