# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0019_auto_20161012_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='estimated_arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
