# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exhibitors", "0019_auto_20180922_1900"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lunchticket",
            options={"ordering": ["pk"]},
        ),
    ]
