# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0020_exhibitor_estimated_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='wants_information_about_events',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='wants_information_about_osqledaren',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='wants_information_about_targeted_marketing',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
