# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exhibitors", "0020_auto_20180929_0916"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exhibitor",
            old_name="hosts",
            new_name="contact_persons",
        ),
    ]
