# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0021_auto_20161012_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitor',
            name='invoice_address_city',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='invoice_address_country',
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='invoice_additional_information',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='invoice_address_po_box',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='invoice_organisation_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='invoice_reference',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='invoice_reference_phone_number',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
