# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exhibitors", "0022_auto_20180929_1127"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cataloguebenefit",
            options={"default_permissions": []},
        ),
        migrations.AlterModelOptions(
            name="catalogueemployment",
            options={"default_permissions": []},
        ),
        migrations.AlterModelOptions(
            name="catalogueindustry",
            options={"default_permissions": []},
        ),
        migrations.AlterModelOptions(
            name="cataloguelocation",
            options={"default_permissions": []},
        ),
        migrations.AlterModelOptions(
            name="cataloguevalue",
            options={"default_permissions": []},
        ),
        migrations.AlterModelOptions(
            name="exhibitorview",
            options={"default_permissions": []},
        ),
        migrations.AlterModelOptions(
            name="lunchticket",
            options={"default_permissions": [], "ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="lunchticketday",
            options={"default_permissions": [], "ordering": ["fair", "name"]},
        ),
        migrations.AlterModelOptions(
            name="lunchticketscan",
            options={"default_permissions": []},
        ),
    ]
