# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0022_auto_20161012_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitor',
            name='transport_from_fair_type',
            field=models.CharField(blank=True, choices=[('third_party_builders_transport', 'We use a third-party to build our stand who will transport our goods from the fair'), ('armada_transport', 'We use Armada Transport'), ('self_transport', 'We will arrange our own transportation immediately after the fair (note that there is limited access for larger transportation services as the fair closes and it may take some time before your equipment can be picked up)')], max_length=300, null=True),
        ),
    ]
