# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0023_auto_20161012_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='transport_from_fair_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='transport_from_fair_recipient',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='transport_from_fair_zip_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
