# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0002_partner_tag'),
        ('exhibitors', '0023_auto_20161012_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='cataloginfo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='fair.Tag'),
        ),
    ]
