# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exhibitors", "0023_auto_20180930_0941"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exhibitor",
            options={
                "default_permissions": [],
                "permissions": [
                    ("base", "View the Exhibitors tab"),
                    ("view_all", "Always view all exhibitors"),
                    ("create", "Create new exhibitors"),
                    ("modify_contact_persons", "Modify contact persons"),
                    ("transport", "Modify exhibitor transport details"),
                ],
            },
        ),
    ]
