# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0024_auto_20161014_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhibitor',
            old_name='transport_from_fair_recipient',
            new_name='transport_from_fair_recipient_name',
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='transport_from_fair_recipient_phone_number',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
