# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0025_auto_20161014_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='estimated_arrival_of_representatives',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
