# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0025_auto_20180930_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitor',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='location_at_fair',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='logo',
        ),
    ]
