# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0026_exhibitor_estimated_arrival_of_representatives'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanquetteAttendant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('phone_number', models.CharField(max_length=200)),
                ('allergies', models.CharField(max_length=1000)),
                ('student_ticket', models.BooleanField(default=False)),
                ('wants_alcohol', models.BooleanField(default=True)),
                ('wants_lactose_free_food', models.BooleanField(default=False)),
                ('wants_gluten_free_food', models.BooleanField(default=False)),
                ('exhibitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibitors.Exhibitor')),
            ],
        ),
    ]
