# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0027_auto_20181011_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='picture_original',
            new_name='background',
        ),
    ]
