# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0027_banquetteattendant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banquetteattendant',
            name='allergies',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='banquetteattendant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
