# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0029_merge_20161018_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='banquetteattendant',
            name='job_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='banquetteattendant',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
