# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0029_auto_20181011_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitor',
            name='transport_from',
            field=models.CharField(choices=[('NOT_BOOKED', 'Not booked'), ('BOOKED', 'Booked'), ('ARKAD', 'Transported by Arkad'), ('NOT_APPLICABLE', 'Not applicable')], default='NOT_BOOKED', max_length=30),
        ),
        migrations.AlterField(
            model_name='exhibitor',
            name='transport_to',
            field=models.CharField(choices=[('NOT_BOOKED', 'Not booked'), ('BOOKED', 'Booked'), ('ARKAD', 'Transported by Arkad'), ('NOT_APPLICABLE', 'Not applicable')], default='NOT_BOOKED', max_length=30),
        ),
    ]
