# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0030_auto_20161022_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banquetteattendant',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
