# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0031_auto_20161023_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cataloginfo',
            name='short_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
