# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibitors", "0031_auto_20181019_1108"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exhibitor",
            name="transport_from",
            field=models.CharField(
                choices=[
                    ("NOT_BOOKED", "Not booked"),
                    ("BOOKED", "Booked"),
                    ("NOT_APPLICABLE", "Not applicable"),
                    ("EXCEPTION", "Exception"),
                    ("IN_CONTACT", "In contact"),
                ],
                default="NOT_BOOKED",
                max_length=30,
            ),
        ),
    ]
