# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 17:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0033_auto_20161025_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banquetteattendant',
            name='exhibitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exhibitors.Exhibitor'),
        ),
        migrations.AlterField(
            model_name='banquetteattendant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
