# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0034_auto_20161025_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='banquetteattendant',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='banquetteattendant',
            name='wants_vegetarian_food',
            field=models.BooleanField(default=False),
        ),
    ]
