# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0034_auto_20181023_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitor',
            name='transport_to',
            field=models.CharField(choices=[('NOT_BOOKED', 'Not booked'), ('BOOKED', 'Booked'), ('ARKAD', 'Transported by Arkad'), ('NOT_APPLICABLE', 'Not applicable'), ('EXCEPTION', 'Exception'), ('IN_CONTACT', 'In contact'), ('IN_CONTACT_ARMADA', 'In contact by Armada')], default='NOT_BOOKED', max_length=30),
        ),
    ]
