# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0035_auto_20161025_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banquetteattendant',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
