# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0036_auto_20161025_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banquetteattendant',
            name='phone_number',
            field=models.CharField(max_length=200),
        ),
    ]
