# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0037_auto_20161025_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banquetteattendant',
            name='wants_vegetarian_food',
            field=models.BooleanField(default=True),
        ),
    ]
