# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0038_auto_20161025_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='banquetteattendant',
            name='seat_number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banquetteattendant',
            name='table_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
