# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0039_auto_20161106_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='banquetteattendant',
            name='ignore_from_placement',
            field=models.BooleanField(default=False),
        ),
    ]
