# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import lib.image


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0040_banquetteattendant_ignore_from_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='cataloginfo',
            name='location_at_fair',
            field=models.ImageField(blank=True, upload_to=lib.image.UploadToDir('exhibitors', 'location_at_fair')),
        ),
        migrations.AddField(
            model_name='cataloginfo',
            name='location_at_fair_original',
            field=models.ImageField(blank=True, upload_to=lib.image.UploadToDirUUID('exhibitors', 'location_at_fair_original')),
        ),
    ]
