# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0041_auto_20161109_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitor',
            name='wants_information_about_events',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exhibitor',
            name='wants_information_about_osqledaren',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exhibitor',
            name='wants_information_about_targeted_marketing',
            field=models.BooleanField(default=False),
        ),
    ]
