# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0041_lunchticket_fair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lunchticket',
            name='exhibitor',
        ),
    ]
