# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20161109_2044'),
        ('exhibitors', '0041_auto_20161109_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='fair_location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
    ]
