# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0042_exhibitor_fair_location'),
        ('exhibitors', '0042_auto_20161109_2235'),
    ]

    operations = [
    ]
