# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0043_merge_20161109_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banquetteattendant',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
    ]
