# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exhibitors", "0044_exhibitor_checked_in"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exhibitor",
            old_name="checked_in",
            new_name="check_in_timestamp",
        ),
    ]
