# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-22 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0045_auto_20161118_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='manual_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
