# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibitors", "0046_auto_20181107_1327"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibitorinbooth",
            name="days",
            field=models.ManyToManyField(to="exhibitors.LunchTicketDay"),
        ),
    ]
