# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0047_banquetteattendant_fair'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
