# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-11 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0048_auto_20181109_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lunchticket',
            name='company',
        ),
        migrations.RemoveField(
            model_name='lunchticket',
            name='day',
        ),
        migrations.RemoveField(
            model_name='lunchticket',
            name='dietary_restrictions',
        ),
        migrations.RemoveField(
            model_name='lunchticket',
            name='fair',
        ),
        migrations.RemoveField(
            model_name='lunchticket',
            name='time',
        ),
        migrations.RemoveField(
            model_name='lunchticket',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lunchticketscan',
            name='lunch_ticket',
        ),
        migrations.RemoveField(
            model_name='lunchticketscan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lunchtickettime',
            name='fair',
        ),
        migrations.DeleteModel(
            name='LunchTicket',
        ),
        migrations.DeleteModel(
            name='LunchTicketScan',
        ),
        migrations.DeleteModel(
            name='LunchTicketTime',
        ),
    ]
