# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-11 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0049_auto_20181111_1246'),
        ('fair', '0005_fairday_lunchticket_lunchticketscan_lunchtickettime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lunchticketday',
            name='fair',
        ),
        migrations.AlterField(
            model_name='exhibitorinbooth',
            name='days',
            field=models.ManyToManyField(to='fair.FairDay'),
        ),
        migrations.DeleteModel(
            name='LunchTicketDay',
        ),
    ]
