# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0049_exhibitor_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='about_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='facts_text',
            field=models.TextField(blank=True),
        ),
    ]
