# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0051_auto_20170530_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='interested_in_armada_transport',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exhibitor',
            name='transport_to_fair_type',
            field=models.CharField(blank=True, choices=[('external_transport', 'Arranged with external delivery firm'), ('arkad_transport', 'Transport from Arkad in Lund'), ('self_transport_small', 'We bring our (only small) goods ourselves'), ('self_transport_large', 'We bring our (large) goods ourselves')], max_length=30, null=True),
        ),
    ]
