# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0052_auto_20170530_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='invoice_purchase_order_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='exhibitor',
            name='transport_from_fair_type',
            field=models.CharField(blank=True, choices=[('third_party_builders_transport', 'We use a third-party to build our stand who will transport our goods from the fair'), ('armada_transport', 'We use Armada Transport'), ('self_transport', 'We only have small goods with us and our representatives will bring it with them when they leave the fair')], max_length=300, null=True),
        ),
    ]
