# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0053_auto_20170603_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitor',
            name='allergies',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
