# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibitors", "0053_auto_20181120_0922"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationtick",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
