# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0054_auto_20170607_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='goals_of_participation',
            field=models.CharField(blank=True, choices=[('employer_branding', 'Employer Branding'), ('recruitment_employees', 'Recruitment of employees'), ('recruitment_master_thesis', 'Recruitment of Master Thesis'), ('recruitment_summer_workers', 'Recruitment of Summer workers')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='offers_bachelor_thesis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='offers_international_opportunities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='offers_master_thesis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='offers_part_time_jobs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='offers_summer_jobs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='offers_trainee_program',
            field=models.BooleanField(default=False),
        ),
    ]
