# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-21 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0057_auto_20170828_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='booth_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
