# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-24 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibitors", "0057_auto_20190722_2257"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibitor",
            name="catalogue_cities",
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
