# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-26 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0058_exhibitor_booth_number'),
    ]

    operations = [
    ]
