# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-27 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0059_exhibitorview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibitorview',
            options={},
        ),
    ]
