# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-30 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0060_auto_20170927_1742'),
        ('exhibitors', '0060_auto_20170926_2021'),
    ]

    operations = [
    ]
