# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-08 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0018_auto_20190921_1508'),
        ('exhibitors', '0062_auto_20191008_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationSpecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('exhibitors', models.ManyToManyField(blank=True, to='exhibitors.Exhibitor')),
                ('fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fair.Fair')),
            ],
            options={
                'verbose_name': 'Special location',
                'default_permissions': [],
            },
        ),
    ]
