# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-12 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0063_auto_20171012_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitor',
            name='transport_to_fair_type',
            field=models.CharField(blank=True, choices=[('external_transport', 'Arranged with external delivery firm'), ('arkad_transport', 'Transport from Arkad in Lund'), ('self_transport_small', 'We bring our (only small) goods ourselves'), ('self_transport_large', 'We bring our (large) goods ourselves'), ('armada_transport_to_fair', 'We use Armada Transport')], max_length=30, null=True),
        ),
    ]
