# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-13 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0018_auto_20190921_1508'),
        ('exhibitors', '0063_locationspecial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateCompensation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Climate Compensation',
                'default_permissions': [],
            },
        ),
        migrations.AlterField(
            model_name='exhibitor',
            name='fair_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exhibitors.Location'),
        ),
        migrations.AddField(
            model_name='climatecompensation',
            name='exhibitors',
            field=models.ManyToManyField(blank=True, to='exhibitors.Exhibitor'),
        ),
        migrations.AddField(
            model_name='climatecompensation',
            name='fair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fair.Fair'),
        ),
    ]
