# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-13 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0064_auto_20191013_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='flyer',
            field=models.FileField(blank=True, default=None, null=True, upload_to='flyers/%Y%m%d/'),
        ),
    ]
