# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-09-29 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exhibitors", "0064_auto_20191028_1240"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exhibitor",
            name="placement_wish",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "No preference"),
                    ("MIXED", "Mixed with companies from other industries"),
                    ("SIMILAR", "Next to similar companies"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
