# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0066_update_room_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitor',
            name='status',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('registered', 'Registered'), ('complete_registration', 'Completed Registration'), ('complete_registration_submit', 'CR - Submitted'), ('complete_registration_start', 'CR - In Progress'), ('complete_registration_terms', 'CR - Accepted Terms'), ('contacted_by_host', 'Contacted by host'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked in'), ('checked_out', 'Checked out'), ('withdrawn', 'Withdrawn')], max_length=30, null=True),
        ),
    ]
