# Generated by Django 2.2.24 on 2023-08-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibitors", "0067_add_transport_information_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exhibitor",
            name="catalogue_contact_email_address",
            field=models.EmailField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Contact person's e-mail address",
            ),
        ),
    ]
