# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    def update_offers(apps, scema_editor):
        Question = apps.get_model('matching', 'Question')
        Response = apps.get_model('matching', 'Response')
        IntegerAns = apps.get_model('matching', 'IntegerAns')

        summer_job_question = Question.objects.filter(name='Number of ').first()
        master_thesis_question = Question.objects.filter(name='Number of mast').first()
        part_time_job_question = Question.objects.filter(name='Number of part t').first()
        trainee_question = Question.objects.filter(name='Number of tr').first()
        job_types = [summer_job_question, master_thesis_question, part_time_job_question, trainee_question]

        for answer in IntegerAns.objects.filter(question__in=job_types):
            if answer.ans >=1:
                exhibitor = answer.response.exhibitor
                if answer.question == summer_job_question:
                    exhibitor.offers_summer_jobs = True
                if answer.question == master_thesis_question:
                    exhibitor.offers_master_thesis = True
                if answer.question == part_time_job_question:
                    exhibitor.offers_part_time_jobs = True
                if answer.question == trainee_question:
                    exhibitor.offers_trainee_program = True
                exhibitor.save()
     

    dependencies = [
        ('exhibitors', '0067_auto_20171030_1602'),
        ('matching', '0031_auto_20171030_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitor',
            name='offers_bachelor_thesis',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='offers_international_opportunities',
        ),

        migrations.RunPython(update_offers)
    ]