# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0068_auto_20171030_1619')
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='job_types',
            field=models.ManyToManyField(blank=True, to='exhibitors.JobType'),
        ),

    ]




















