# Generated by Django 2.2.24 on 2023-09-19 19:19

from django.contrib.postgres.fields import JSONField

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exhibitors", "0068_auto_20230816_0013"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exhibitor",
            options={
                "default_permissions": [],
                "ordering": ["company__name"],
                "permissions": [
                    ("base", "View the Exhibitors tab"),
                    ("view_all", "Always view all exhibitors"),
                    ("create", "Create new exhibitors"),
                    ("modify_contact_persons", "Modify contact persons"),
                    ("modify_transport", "Modify transport details"),
                    ("modify_check_in", "Modify check in"),
                    ("modify_details", "Modify details"),
                    ("modify_booths", "Modify booths"),
                    ("people_count", "Count people in locations"),
                    ("modify_coordinates", "Modify coordinates"),
                ],
            },
        ),
        migrations.AddField(
            model_name="exhibitor",
            name="map_coordinates",
            field=JSONField(blank=True, null=True),
        ),
    ]
