# Generated by Django 2.2.24 on 2023-09-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0068_auto_20230816_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='map_coordinates_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='map_coordinates_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
