# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0070_exhibitor_job_types2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitor',
            name='offers_master_thesis',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='offers_part_time_jobs',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='offers_summer_jobs',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='offers_trainee_program',
        ),
    ]
