# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0027_invoicedetails'),
        ('exhibitors', '0071_auto_20171030_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='invoice_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.InvoiceDetails'),
        ),
    ]
