# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0027_invoicedetails'),
        ('exhibitors', '0072_exhibitor_invoice_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitor',
            name='invoice_additional_information',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='invoice_address',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='invoice_address_po_box',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='invoice_address_zip_code',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='invoice_identification',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='invoice_organisation_name',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='invoice_purchase_order_number',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='invoice_reference',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='invoice_reference_phone_number',
        ),
    ]
