# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0073_auto_20180121_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportationAlternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('transportation_type', models.CharField(blank=True, choices=[('3rd_party', 'Third party'), ('self', 'By Customer'), ('internal', 'Fair arranger')], max_length=30, null=True)),
                ('inbound', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='inbound_transportation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_transportation', to='exhibitors.TransportationAlternative'),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='outbound_transportation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_transportation', to='exhibitors.TransportationAlternative'),
        ),
    ]
