# Generated by Django 2.2.24 on 2024-07-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exhibitors", "0074_add_application_status_perm"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exhibitor",
            options={
                "default_permissions": [],
                "ordering": ["company__name"],
                "permissions": [
                    ("base", "View the Exhibitors tab"),
                    ("view_all", "Always view all exhibitors"),
                    ("create", "Create new exhibitors"),
                    ("modify_contact_persons", "Modify contact persons"),
                    ("modify_transport", "Modify transport details"),
                    ("modify_check_in", "Modify check in"),
                    ("modify_details", "Modify details"),
                    ("modify_booths", "Modify booths"),
                    ("people_count", "Count people in locations"),
                    ("modify_coordinates", "Modify coordinates"),
                    ("modify_fair_location", "Modify Fair Location"),
                    ("modify_application_status", "Modify application status"),
                ],
            },
        ),
        migrations.AlterField(
            model_name="exhibitor",
            name="application_status",
            field=models.CharField(
                choices=[
                    ("0", "pending"),
                    ("1", "accepted"),
                    ("2", "rejected"),
                    ("3", "waitlist"),
                ],
                default="0",
                max_length=255,
            ),
        ),
    ]
