# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0074_auto_20180128_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitor',
            name='inbound_transportation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_transportation', to='exhibitors.TransportationAlternative', verbose_name='Transportation to the fair'),
        ),
        migrations.AlterField(
            model_name='exhibitor',
            name='outbound_transportation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_transportation', to='exhibitors.TransportationAlternative', verbose_name='Transportation from the fair'),
        ),
    ]
