# Generated by Django 2.2.24 on 2024-09-25 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0073_addExhibitorChat'),
        ('exhibitors', '0075_change_exhibitor_application_status'),
    ]

    operations = [
    ]
