# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0004_remove_transportationorder_company'),
        ('exhibitors', '0075_auto_20180128_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='delivery_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_order', to='transportation.TransportationOrder'),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='pickup_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_order', to='transportation.TransportationOrder'),
        ),
    ]
