# Generated by Django 2.2.24 on 2024-10-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0075_change_exhibitor_application_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exhibitorinbooth',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='exhibitorinbooth',
            name='booth',
        ),
        migrations.RemoveField(
            model_name='exhibitorinbooth',
            name='days',
        ),
        migrations.RemoveField(
            model_name='exhibitorinbooth',
            name='exhibitor',
        ),
        migrations.DeleteModel(
            name='Booth',
        ),
        migrations.DeleteModel(
            name='ExhibitorInBooth',
        ),
    ]
