# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0076_auto_20180128_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitor',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='estimated_arrival',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='estimated_arrival_of_representatives',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='goals_of_participation',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='interested_in_armada_transport',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='manual_invoice',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='number_of_packages_from_fair',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='number_of_packages_to_fair',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='number_of_pallets_from_fair',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='number_of_pallets_to_fair',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='other_information_about_the_stand',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='requests_for_exhibition_area',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='requests_for_stand_placement',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='transport_from_fair_address',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='transport_from_fair_recipient_name',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='transport_from_fair_recipient_phone_number',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='transport_from_fair_type',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='transport_from_fair_zip_code',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='transport_to_fair_type',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='wants_information_about_events',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='wants_information_about_osqledaren',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='wants_information_about_targeted_marketing',
        ),
    ]
