# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0077_auto_20180128_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitor',
            name='heavy_duty_electric_equipment',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='number_of_outlets_needed',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='total_power',
        ),
    ]
