# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0078_auto_20180129_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitor',
            name='delivery_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_order', to='transportation.TransportationOrder'),
        ),
        migrations.AlterField(
            model_name='exhibitor',
            name='inbound_transportation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_transportation', to='exhibitors.TransportationAlternative', verbose_name='Transportation to the fair'),
        ),
        migrations.AlterField(
            model_name='exhibitor',
            name='outbound_transportation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_transportation', to='exhibitors.TransportationAlternative', verbose_name='Transportation from the fair'),
        ),
        migrations.AlterField(
            model_name='exhibitor',
            name='pickup_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_order', to='transportation.TransportationOrder'),
        ),
    ]
