# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0079_auto_20180131_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibitor',
            options={'permissions': (('base', 'Exhibitors'),)},
        ),
    ]
