# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0080_auto_20180324_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitor',
            name='invoice_details',
        ),
    ]
