# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('room', models.CharField(max_length=75)),
                ('floor', models.CharField(max_length=75)),
                ('building', models.CharField(max_length=75)),
                ('address', models.CharField(max_length=75)),
                ('capacity', models.IntegerField(blank=True, default=1, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
