# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("unirel", "0002_auto_20181029_1213"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="phone_number",
            field=models.CharField(default=1, max_length=75),
            preserve_default=False,
        ),
    ]
