# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("unirel", "0004_auto_20181029_1223"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="participant",
            options={"ordering": ["fair", "name"]},
        ),
    ]
