# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("unirel", "0005_auto_20181029_1241"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="addon_banquet",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], default=False
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="addon_lunch",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], default=False
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="addon_sleep",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], default=False
            ),
        ),
    ]
