# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("unirel", "0006_auto_20181029_1242"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="participant",
            options={
                "ordering": ["fair", "name"],
                "permissions": [("base", "University relations")],
            },
        ),
    ]
