# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("unirel", "0008_auto_20181029_1308"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="participant",
            options={
                "ordering": ["fair", "company", "name"],
                "permissions": [("base", "University relations")],
            },
        ),
    ]
