# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exhibitors', '0001_initial'),
        ('fair', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_power', models.IntegerField(default=0)),
                ('number_of_outlets', models.IntegerField(default=0)),
                ('equipment_description', models.CharField(blank=True, max_length=150, null=True)),
                ('exhibitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibitors.Exhibitor')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('exhibitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibitors.Exhibitor')),
            ],
            options={
                'ordering': ['product'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('coa_number', models.PositiveSmallIntegerField()),
                ('price', models.IntegerField()),
                ('display_in_product_list', models.BooleanField(default=True)),
                ('included_for_all', models.BooleanField(default=False)),
            ],
            options={
                'permissions': (('base', 'Products'),),
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('selection_policy', models.CharField(choices=[('SELECT', 'Select one'), ('SELECT_MULTIPLE', 'Select multipe'), ('SELECT_MULTIPLE_Amount', 'Select multipe with amount')], default='SELECT', max_length=25)),
                ('display_in_product_list', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StandArea',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Product')),
                ('width', models.IntegerField()),
                ('depth', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
            bases=('orders.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='fair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fair.Fair'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.ProductType'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Product'),
        ),
    ]
