# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20161011_2252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': (('view_products', 'View products'),)},
        ),
    ]
