# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20170516_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='formView',
        ),
    ]
