# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20170525_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandArea',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Product')),
                ('width', models.IntegerField()),
                ('depth', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
            bases=('orders.product',),
        ),
    ]
