# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20180127_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='selection_policy',
            field=models.CharField(choices=[('SELECT', 'Select one'), ('SELECT_MULTIPLE', 'Select multipe')], default='SELECT', max_length=20),
        ),
    ]
