# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_producttype_selection_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='display_in_product_list',
            field=models.BooleanField(default=False),
        ),
    ]
