# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_producttype_display_in_product_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_in_product_list',
            field=models.BooleanField(default=True),
        ),
    ]
