# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_product_display_in_product_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='selection_policy',
            field=models.CharField(choices=[('SELECT', 'Select one'), ('SELECT_MULTIPLE', 'Select multipe'), ('SELECT_MULTIPLE_Amount', 'Select multipe with amount')], default='SELECT', max_length=25),
        ),
    ]
