# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_electricityorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='included_for_all',
            field=models.BooleanField(default=False),
        ),
    ]
