# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 13:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounting", "0001_initial"),
        ("companies", "0001_initial"),
        ("fair", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="purchasing_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="companies.Company",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="purchasing_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="companies.CompanyAddress",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="company_customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="companies.CompanyCustomer",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="fair",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fair.Fair"
            ),
        ),
    ]
