# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.CompanyAddress'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.CompanyCustomer'),
        ),
    ]
