# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0036_auto_20180403_1340'),
        ('fair', '0008_auto_20180110_1850'),
        ('accounting', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_display', models.PositiveIntegerField(unique=True)),
                ('price', models.PositiveIntegerField()),
                ('date_issue', models.DateField()),
                ('date_due', models.DateField()),
                ('date_delivery_start', models.DateField()),
                ('date_delivery_end', models.DateField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.CompanyAddress')),
                ('company_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.CompanyCustomer')),
            ],
            options={
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='ProductOnInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Product')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='revenue',
            name='fair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fair.Fair'),
        ),
    ]
