# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-06 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0002_auto_20180730_1515"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
