# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20180403_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='fair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fair.Fair'),
        ),
    ]
