# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0003_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="revenue",
            name="description",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
