# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_auto_20180814_1700"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationsection",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
