# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20180729_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='description',
        ),
    ]
