# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0001_initial'),
        ('accounting', '0007_auto_20180815_0905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revenue',
            options={'ordering': ['fair__year', 'name'], 'verbose_name_plural': 'Revenues'},
        ),
        migrations.AlterUniqueTogether(
            name='revenue',
            unique_together=set([('name', 'fair')]),
        ),
    ]
