# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_remove_revenue_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
