# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0008_auto_20180815_0910"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="unit_price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_price",
            field=models.IntegerField(),
        ),
    ]
