# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0009_auto_20180815_0937"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "permissions": [("base", "Accounting")],
                "verbose_name_plural": "Products",
            },
        ),
    ]
