# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 20:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0081_auto_20180708_1114'),
        ('accounting', '0009_auto_20180729_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchasing_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='order',
            name='purchasing_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
