# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0010_auto_20180815_1033"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="cost_center",
            new_name="cost_unit",
        ),
    ]
