# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_auto_20180729_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='revenue',
        ),
    ]
