# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0011_auto_20180815_1123"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="invoiced",
            field=models.BooleanField(default=False),
        ),
    ]
