# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 10:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0012_order_invoiced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoninvoice',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='productoninvoice',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='company_customer',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='date_delivery_end',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='date_delivery_start',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='date_due',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='date_issue',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='id_display',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='invoiced',
        ),
        migrations.AddField(
            model_name='invoice',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Invoice'),
        ),
        migrations.DeleteModel(
            name='ProductOnInvoice',
        ),
    ]
