# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0015_auto_20181128_1115"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Invoice",
            new_name="ExportBatch",
        ),
        migrations.AlterModelOptions(
            name="exportbatch",
            options={"default_permissions": [], "ordering": ["timestamp"]},
        ),
        migrations.RenameField(
            model_name="order",
            old_name="invoice",
            new_name="export_batch",
        ),
    ]
