# Generated by Django 2.2.24 on 2021-09-18 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0020_auto_20191210_1634"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="export_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.ExportBatch",
            ),
        ),
    ]
