# Generated by Django 2.2.24 on 2023-08-12 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0024_add_child_product_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="childproduct",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="revenue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounting.Revenue"
            ),
        ),
    ]
