# Generated by Django 2.2.24 on 2023-08-16 00:30

import accounting.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0027_add_account_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="exclusively_for",
            field=accounting.models.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("ir-signed", "Companies who have signed IR"),
                        ("ir-unsigned", "Companies who have NOT signed IR"),
                    ],
                    max_length=31,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
