# Generated by Django 2.2.24 on 2023-08-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0030_add_product_short_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
