# Generated by Django 2.2.24 on 2023-08-16 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0031_add_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="order",
            name="stock_when_bought",
            field=models.IntegerField(
                blank=True,
                help_text="When this order was placed, what was the stock level of the product?",
                null=True,
            ),
        ),
    ]
