# Generated by Django 2.2.24 on 2024-08-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0035_add_specific_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
