# Generated by Django 2.2.24 on 2024-08-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0036_add_specific_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childproduct',
            name='description',
            field=models.TextField(blank=True, help_text='Optional, describe why you created this child product. This will not be shown to the customer.', null=True),
        ),
        migrations.AlterField(
            model_name='specificproduct',
            name='description',
            field=models.TextField(blank=True, help_text='Optional, describe why you created this specific product. This will not be shown to the customer.', null=True),
        ),
    ]
