# Generated by Django 2.2.24 on 2024-08-04 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0038_add_display_only_when_specific_for_packages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="display_only_when_specific_for_packages",
        ),
    ]
