# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Armada 2016', max_length=100)),
                ('year', models.IntegerField(default=2016)),
            ],
        ),
    ]
