# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fair',
            name='year',
            field=models.IntegerField(default=1970),
        ),
    ]
