# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lib.image


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to=lib.image.UploadToDirUUID('partners', 'logo'))),
                ('url', models.CharField(max_length=300)),
                ('main_partner', models.BooleanField()),
                ('fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fair.Fair')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
