# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fair", "0003_organizationgroup"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organizationgroup",
            options={"ordering": ["fair", "name"]},
        ),
    ]
