# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0003_auto_20170218_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='fair',
            name='description',
            field=models.TextField(default='Armada 2017', max_length=500),
        ),
        migrations.AddField(
            model_name='fair',
            name='registration_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='fair',
            name='registration_start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
