# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0004_auto_20170305_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='fair',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
