# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-31 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0005_fair_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='fair',
            name='complete_registration_close_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fair',
            name='complete_registration_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
