# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-11 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0006_fairday2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fairday2',
            name='fair',
        ),
        migrations.DeleteModel(
            name='FairDay2',
        ),
    ]
