# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-11 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0008_auto_20181111_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lunchticket',
            options={'default_permissions': [], 'ordering': ['pk'], 'permissions': [('lunchtickets', 'Manage lunch tickets')]},
        ),
        migrations.AddField(
            model_name='lunchticket',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
