# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fair", "0011_lunchticket_sent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lunchticket",
            name="sent",
        ),
    ]
