# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 13:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fair", "0012_remove_lunchticket_sent"),
    ]

    operations = [
        migrations.CreateModel(
            name="LunchTicketSend",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("email_address", models.CharField(max_length=255)),
            ],
            options={
                "default_permissions": [],
            },
        ),
        migrations.AddField(
            model_name="lunchticket",
            name="sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lunchticketsend",
            name="lunch_ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fair.LunchTicket"
            ),
        ),
        migrations.AddField(
            model_name="lunchticketsend",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
