# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0013_auto_20181117_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunchticketsend',
            name='email_address',
            field=models.EmailField(max_length=255, verbose_name='E-mail address'),
        ),
    ]
