# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-01 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0014_auto_20181117_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fair',
            name='year',
            field=models.IntegerField(default=2019),
        ),
    ]
