# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-21 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fair", "0016_auto_20190320_0909"),
    ]

    operations = [
        migrations.AddField(
            model_name="lunchticket",
            name="dietary_restrictions_other",
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
