# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-10 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fair", "0018_auto_20190921_1508"),
    ]

    operations = [
        migrations.AddField(
            model_name="fair",
            name="companies_ticket_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="After this date the companies will no longer be able to create or edit their lunch or banquet tickets on their registration page.",
                null=True,
            ),
        ),
    ]
