# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-29 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fair", "0019_fair_companies_ticket_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fair",
            name="year",
            field=models.IntegerField(default=2020),
        ),
    ]
