# Generated by Django 2.2.24 on 2023-04-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0021_auto_20210918_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fair',
            name='year',
            field=models.IntegerField(default=2023),
        ),
    ]
