# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='nickname',
            field=models.CharField(max_length=100),
        ),
    ]
