# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-16 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0025_auto_20170410_1307'),
        ('fair', '0006_auto_20170831_2211'),
        ('student_profiles', '0002_auto_20170930_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fair.Fair')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profiles.StudentProfile')),
            ],
            options={
                'verbose_name': 'results matching',
                'default_permissions': (),
            },
        ),
    ]
