# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0064_exhibitor_location_at_fair'),
        ('student_profiles', '0003_matchingresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchingresult',
            name='company',
        ),
        migrations.AddField(
            model_name='matchingresult',
            name='exhibitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exhibitors.Exhibitor'),
        ),
    ]
