# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-01 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profiles', '0004_auto_20171026_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='nickname',
            field=models.CharField(max_length=512),
        ),
    ]
