# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-28 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profiles', '0004_auto_20171026_2249'),
        ('student_profiles', '0004_auto_20171029_0057'),
    ]

    operations = [
    ]
