# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-02 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profiles', '0005_auto_20171101_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='facebook_profile',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='linkedin_profile',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
