# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-04 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import uuid

def delete_old_students(apps, schema_editor):
    StudentProfile = apps.get_model('student_profiles', 'StudentProfile')
    StudentProfile.objects.all().delete()
    

class Migration(migrations.Migration):

    dependencies = [
        ('student_profiles', '0006_auto_20171102_1045'),
    ]

    operations = [
        migrations.RunPython(delete_old_students),
    ]
