# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-03 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student_profiles', '0006_auto_20171102_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='id_string',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
