# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-04 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student_profiles', '0007_auto_20171103_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='id_string',
            field=models.UUIDField(primary_key=False, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
