# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-09 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profiles', '0008_auto_20171105_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='classifier_log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
