# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-05 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profiles', '0010_auto_20171105_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='id',
            new_name='student_id',
        ),
    ]
