# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-05 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profiles', '0012_auto_20171105_1914'),
    ]

    operations = [
    ]
