# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 18:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exhibitors', '0003_exhibitor_location'),
        ('sales', '0002_auto_20161026_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('contact_them', 'Contact them'), ('contact_us', 'Contact us'), ('no_follow_up', 'No follow up')], default=None, max_length=30, null=True)),
                ('follow_up_date', models.DateTimeField(blank=True, default=sales.models.one_week_ahead)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_contacted', 'Not contacted'), ('unreachable', 'Unreachable'), ('not_interested', 'Not interested'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('will_register', 'Will register'), ('registered', 'Registered'), ('fa_contacted', 'FA contacted'), ('fa_on_the_go', 'FA on the go'), ('pending_ad_approval', 'Pending ad approval'), ('ad_sent_for_approval', 'Ad sent for approval'), ('ad_wrong', 'Ad wrong'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='not_contacted', max_length=30, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Campaign')),
                ('exhibitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibitors.Exhibitor')),
                ('responsible', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True, null=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Sale')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='sales',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='exhibitor',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='responsible',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
