# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20161109_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('Not contacted', 'Not contacted'), ('Unreachable', 'Unreachable'), ('Not interested', 'Not interested'), ('Contacted', 'Contacted'), ('Interested', 'Interested'), ('Will register', 'Will register'), ('Registered', 'Registered'), ('FA contacted', 'FA contacted'), ('FA on the go', 'FA on the go'), ('Pending ad approval', 'Pending ad approval'), ('Ad sent for approval', 'Ad sent for approval'), ('Ad wrong', 'Ad wrong'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='not_contacted', max_length=30, null=True),
        ),
    ]
