# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-18 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_contact_belongs_to'),
        ('sales', '0006_auto_20161118_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='exhibitor',
        ),
        migrations.AddField(
            model_name='sale',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
            preserve_default=False,
        ),
    ]
