# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def copy_fair_relation(apps, schema_editor):
    Campaign = apps.get_model('sales', 'Campaign')
    db_alias = schema_editor.connection.alias
    for campaign in Campaign.objects.using(db_alias).all():
        campaign.fair = campaign.sales_period.fair
        campaign.save()

def reverse_change(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0003_auto_20170218_2244'),
        ('sales', '0007_auto_20170218_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='fair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fair.Fair'),
        ),
        migrations.RunPython(copy_fair_relation, reverse_change),
    ]
