# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_campaign_fair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesperiod',
            name='fair',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='sales_period',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='fair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fair.Fair'),
        ),
        migrations.DeleteModel(
            name='SalesPeriod',
        ),
    ]
