# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20170306_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='preliminary_registration',
            field=models.BooleanField(default=False),
        ),
    ]
