# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fair.models


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0005_fair_current'),
        ('sales', '0012_auto_20170306_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='preliminary_registration',
        ),
        migrations.AddField(
            model_name='sale',
            name='fair',
            field=models.ForeignKey(default=fair.models.current_fair, null=True, on_delete=django.db.models.deletion.CASCADE, to='fair.Fair'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Campaign'),
        ),
    ]
