# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0005_fair_current'),
        ('sales', '0013_auto_20170306_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='fair',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='fair.Fair'),
        ),
    ]
