# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_auto_20170308_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='diversity_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='events',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='green_room',
            field=models.BooleanField(default=False),
        ),
    ]
