# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_sale_fair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='preliminary_registration',
        ),
    ]
