# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_auto_20170330_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='fair',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='campaign',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
    ]
