# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_auto_20170330_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='nova',
            field=models.BooleanField(default=False),
        ),
    ]
