# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_sale_nova'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='contact_by_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
