# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_sale_nova'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='registration_status',
            field=models.BooleanField(default=False),
        ),
    ]
