# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_auto_20170522_1729'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuisnessArea',
            new_name='BusinessArea',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='buisness_area',
            new_name='business_area',
        ),
    ]
