# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_sale_registration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='registration_status',
            field=models.CharField(default='not_registered', max_length=30),
        ),
    ]
